### PR TITLE
Allow signal handler to work on AWS

### LINKED ISSUE #841: [native-image] naitive doesn't run in AWS Lambda custrom runtime beacuse of "Util_sun_misc_Signal.ensureInitialized: CSunMiscSignal.open() failed."
I tried running naitive image in  AWS Lambda custrom runtime.
But it did not run.  Error Summary is bellow.

```
Util_sun_misc_Signal.ensureInitialized: CSunMiscSignal.create() failed. errno: 38 Function not implemented
VMError.shouldNotReachHere: Util_sun_misc_Signal.ensureInitialized: CSunMiscSignal.open() failed.
```

Sample code is bellow:

```java
package sample;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello Graal " + args[0]);
    }
}
```
Then, build native image command is bellow:

```
native-image --no-server \
            --class-path aws-graal.jar \
	     -H:EnableURLProtocols=http \
	     -H:Name=aws-graal \
	     -H:Class=sample.Main \
	     -H:+ReportUnsupportedElementsAtRuntime \
	     -H:+AllowVMInspection
```

I run native-image in  Docker oracle/graalvm-ce:1.0.0-rc9 .
And this image run in local.

lambda's full log is bellow:

```
START RequestId: 2fef123c-f827-11e8-ad2a-13d1ebd52648 Version: $LATEST
Util_sun_misc_Signal.ensureInitialized: CSunMiscSignal.create() failed. errno: 38 Function not implemented
VMError.shouldNotReachHere: Util_sun_misc_Signal.ensureInitialized: CSunMiscSignal.open() failed.

JavaFrameAnchor dump:

No anchors

DeoptStubPointer address: 0000000000000000

TopFrame info:

Lookup TotalFrameSize in CodeInfoTable:
SourceTotalFrameSize 96

VMThreads info:

VMThread 0000000001899010 STATUS_IN_JAVA (safepoints disabled) java.lang.Thread@0x7fe894099ea0

VM Thread State for current thread 0000000001899010:

0 (8 bytes): com.oracle.svm.jni.JNIThreadLocalEnvironment.jniFunctions = (bytes) 
0000000001899010: 0000000000000000

8 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.pinnedTLAB = (bytes) 
0000000001899018: 0000000000000000 0000000000000000
0000000001899028: 0000000000000000 0000000000000000


40 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.regularTLAB = (bytes) 
0000000001899038: 00007fe893c00000 00007fe893d00000
0000000001899048: 00007fe893c01490 0000000000000000


72 (8 bytes): com.oracle.svm.core.genscavenge.PinnedAllocatorImpl.openPinnedAllocator = (Object) null
80 (8 bytes): com.oracle.svm.core.heap.NoAllocationVerifier.openVerifiers = (Object) null
88 (8 bytes): com.oracle.svm.core.jdk.IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) null
96 (8 bytes): com.oracle.svm.core.snippets.SnippetRuntime.currentException = (Object) null
104 (8 bytes): com.oracle.svm.core.thread.JavaThreads.currentThread = (Object) java.lang.Thread 00007fe894099ea0
112 (8 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.activeTimer = (Object) null
120 (8 bytes): com.oracle.svm.jni.JNIThreadLocalHandles.handles = (Object) null
128 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPendingException.pendingException = (Object) null
136 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null
144 (8 bytes): com.oracle.svm.jni.JNIThreadOwnedMonitors.ownedMonitors = (Object) null
152 (8 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.freeList = (Word) 0 0000000000000000
160 (8 bytes): com.oracle.svm.core.stack.JavaFrameAnchors.lastAnchor = (Word) 0 0000000000000000
168 (8 bytes): com.oracle.svm.core.thread.VMThreads.IsolateTL = (Word) 140636889464832 00007fe893d6c000
176 (8 bytes): com.oracle.svm.core.thread.VMThreads.OSThreadIdTL = (Word) 140636912592704 00007fe89537a740
184 (8 bytes): com.oracle.svm.core.thread.VMThreads.nextTL = (Word) 0 0000000000000000
192 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequested = (int) -8883 ffffdd4d
196 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequestedValueBeforeSafepoint = (int) 0 00000000
200 (4 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.currentPauseDepth = (int) 0 00000000
204 (4 bytes): com.oracle.svm.core.thread.VMOperationControl.isLockOwner = (int) 0 00000000
208 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.safepointsDisabledTL = (int) 1 00000001
212 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.statusTL = (int) 1 00000001

VMOperation dump:

No VMOperation in progress


RuntimeCodeCache dump:

== [Recent RuntimeCodeCache operations: ]

== [RuntimeCodeCache: 0 methods]

Deoptimizer dump:

== [Recent Deoptimizer Events: 
]

Dump Counters:


Raw Stacktrace:

00007ffe5a23fa20: 0000000000000001 00007ffe5a23fa90
00007ffe5a23fa30: 00007fe893d6c168 0000000000441eef
00007ffe5a23fa40: 0000000000000026 0000000000000026
00007ffe5a23fa50: 0000000000000001 00007fe893f6c998
00007ffe5a23fa60: 00007fe8940310c8 00007fe893d6c000
00007ffe5a23fa70: 00007fe893f6fd00 00000000004772df
00007ffe5a23fa80: 00000000002c0b38 00007fe8940310c8
00007ffe5a23fa90: 00007fe893f6fd00 000000000046089e
00007ffe5a23faa0: 00007fe893d6c000 00007fe8940310c8
00007ffe5a23fab0: 0000002694111c78 00007fe8940310c8
00007ffe5a23fac0: 0000000000000000 ffffffff00000000
00007ffe5a23fad0: 00007fe89409b010 00007ffe5a23faa0
00007ffe5a23fae0: 0000000000000000 00000000004612de
00007ffe5a23faf0: 0000000000000000 0000000000000000
00007ffe5a23fb00: 00007fe893c01130 00007ffe5a23fb10
00007ffe5a23fb10: 000000000040c670 0000000000000000
00007ffe5a23fb20: 00007ffe5a23fb70 00007ffe5a384e47
00007ffe5a23fb30: 0000000000000000 00007fe893f6c3f8
00007ffe5a23fb40: 0000000000000000 00000000006c0246
00007ffe5a23fb50: 00007ffe5a23fb90 0000000000000001
00007ffe5a23fb60: 0000000000000032 00007fe893f6c3f8
00007ffe5a23fb70: 00007fe893c01478 00000000004033f9
00007ffe5a23fb80: 0000000000000000 00000000004d4646
00007ffe5a23fb90: 00007fe893c01478 0000000000409309
00007ffe5a23fba0: 0000000000095729 00000000004092de
00007ffe5a23fbb0: 00007fe893f583b8 00007ffe5a23fba0
00007ffe5a23fbc0: 00007fe893f58138 000000000043ea1d
00007ffe5a23fbd0: 00007fe893f70120 0000000400000003
00007ffe5a23fbe0: 00007fe893f58138 00007fe894112030
00007ffe5a23fbf0: 00007fe894099f50 0000000000404b69
00007ffe5a23fc00: 00007fe893d6c158 00007fe893d6c000
00007ffe5a23fc10: 00000000000000d8 0000000000437239
00007ffe5a23fc20: 00007fe893c010c8 00007fe893c010c8
00007ffe5a23fc30: 00007fe893f6c568 00007ffe5a23fd88
00007ffe5a23fc40: 0000000293d6c000 000000000040bea9
00007ffe5a23fc50: 0000000000000000 00007fe8951753a7
00007ffe5a23fc60: 0000000000000001 00007ffe5a23fd88
00007ffe5a23fc70: 000000022f2f2f2f 0000000000000000
00007ffe5a23fc80: 0000000000000000 0000000000000000
00007ffe5a23fc90: 00007ffe5a23fd80 0000000000402000
00007ffe5a23fca0: 0000000000000000 00007fe894347c05
00007ffe5a23fcb0: 0000000000000000 00007ffe5a23fd88
00007ffe5a23fcc0: 0000000200000000 000000000040be30
00007ffe5a23fcd0: 0000000000000000 ef2543c0fea25749
00007ffe5a23fce0: 0000000000402000 00007ffe5a23fd80
00007ffe5a23fcf0: 0000000000000000 0000000000000000
00007ffe5a23fd00: 10d9f78707c25749 10f46ba809d85749
00007ffe5a23fd10: 00007ffe00000000 0000000000000000
00007ffe5a23fd20: 0000000000000000 00000000007ba430
00007ffe5a23fd30: 00007ffe5a23fd88 0000000000000002
00007ffe5a23fd40: 0000000000000000 0000000000000000
00007ffe5a23fd50: 0000000000402000 00007ffe5a23fd80
00007ffe5a23fd60: 0000000000000000 0000000000402029
00007ffe5a23fd70: 00007ffe5a23fd78 000000000000001c
00007ffe5a23fd80: 0000000000000002 00007ffe5a240acf
00007ffe5a23fd90: 00007ffe5a240ae3 0000000000000000
00007ffe5a23fda0: 00007ffe5a240b08 00007ffe5a240b2c
00007ffe5a23fdb0: 00007ffe5a240ca7 00007ffe5a240cd7
00007ffe5a23fdc0: 00007ffe5a240cf2 00007ffe5a240d53
00007ffe5a23fdd0: 00007ffe5a240d79 00007ffe5a240dc9
00007ffe5a23fde0: 00007ffe5a240df3 00007ffe5a240e16
00007ffe5a23fdf0: 00007ffe5a240e42 00007ffe5a240e64
00007ffe5a23fe00: 00007ffe5a240e72 00007ffe5a240eb1
00007ffe5a23fe10: 00007ffe5a240ed1 00007ffe5a240ee2

Stacktrace Stage0:

RSP 00007ffe5a23fa20 RIP 0000000000440b3b FrameSize 96
RSP 00007ffe5a23fa80 RIP 00000000004772df FrameSize 32
RSP 00007ffe5a23faa0 RIP 000000000046089e FrameSize 80
RSP 00007ffe5a23faf0 RIP 00000000004612de FrameSize 96
RSP 00007ffe5a23fb50 RIP 00000000006c0246 FrameSize 48
RSP 00007ffe5a23fb80 RIP 00000000004033f9 FrameSize 32
RSP 00007ffe5a23fba0 RIP 0000000000409309 FrameSize 16
RSP 00007ffe5a23fbb0 RIP 00000000004092de FrameSize 32
RSP 00007ffe5a23fbd0 RIP 000000000043ea1d FrameSize 48
RSP 00007ffe5a23fc00 RIP 0000000000404b69 FrameSize 80
RSP 00007ffe5a23fc50 RIP 000000000040bea9 FrameSize 1

Stacktrace Stage1:

RSP 00007ffe5a23fa20 RIP 0000000000440b3b com.oracle.svm.core.code.ImageCodeInfo@0x7fe893ffb650 name = image code
RSP 00007ffe5a23fa80 RIP 00000000004772df com.oracle.svm.core.code.ImageCodeInfo@0x7fe893ffb650 name = image code
RSP 00007ffe5a23faa0 RIP 000000000046089e com.oracle.svm.core.code.ImageCodeInfo@0x7fe893ffb650 name = image code
RSP 00007ffe5a23faf0 RIP 00000000004612de com.oracle.svm.core.code.ImageCodeInfo@0x7fe893ffb650 name = image code
RSP 00007ffe5a23fb50 RIP 00000000006c0246 com.oracle.svm.core.code.ImageCodeInfo@0x7fe893ffb650 name = image code
RSP 00007ffe5a23fb80 RIP 00000000004033f9 com.oracle.svm.core.code.ImageCodeInfo@0x7fe893ffb650 name = image code
RSP 00007ffe5a23fba0 RIP 0000000000409309 com.oracle.svm.core.code.ImageCodeInfo@0x7fe893ffb650 name = image code
RSP 00007ffe5a23fbb0 RIP 00000000004092de com.oracle.svm.core.code.ImageCodeInfo@0x7fe893ffb650 name = image code
RSP 00007ffe5a23fbd0 RIP 000000000043ea1d com.oracle.svm.core.code.ImageCodeInfo@0x7fe893ffb650 name = image code
RSP 00007ffe5a23fc00 RIP 0000000000404b69 com.oracle.svm.core.code.ImageCodeInfo@0x7fe893ffb650 name = image code
RSP 00007ffe5a23fc50 RIP 000000000040bea9 com.oracle.svm.core.code.ImageCodeInfo@0x7fe893ffb650 name = image code

Full Stacktrace:

RSP 00007ffe5a23fa20 RIP 0000000000440b3b [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shutdown(VMErrorSubstitutions.java:146)
RSP 00007ffe5a23fa80 RIP 00000000004772df [image code] com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.shouldNotReachHere(VMErrorSubstitutions.java:63)
RSP 00007ffe5a23faa0 RIP 000000000046089e [image code] com.oracle.svm.core.posix.Util_jdk_internal_misc_Signal.ensureInitialized(SunMiscSubstitutions.java:171)
RSP 00007ffe5a23faf0 RIP 00000000004612de [image code] com.oracle.svm.core.posix.Util_jdk_internal_misc_Signal.numberFromName(SunMiscSubstitutions.java:218)
RSP 00007ffe5a23fb50 RIP 00000000006c0246 [image code] com.oracle.svm.core.posix.Target_jdk_internal_misc_Signal.findSignal(SunMiscSubstitutions.java:74)
RSP 00007ffe5a23fb50 RIP 00000000006c0246 [image code] sun.misc.Signal.<init>(Signal.java:140)
RSP 00007ffe5a23fb80 RIP 00000000004033f9 [image code] com.oracle.svm.core.DumpAllStacks.install(VMInspection.java:87)
RSP 00007ffe5a23fba0 RIP 0000000000409309 [image code] com.oracle.svm.core.VMInspection.lambda$beforeAnalysis$0(VMInspection.java:68)
RSP 00007ffe5a23fbb0 RIP 00000000004092de [image code] com.oracle.svm.core.VMInspection$$Lambda$148/1175531108.run(Unknown Source)
RSP 00007ffe5a23fbd0 RIP 000000000043ea1d [image code] com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:142)
RSP 00007ffe5a23fc00 RIP 0000000000404b69 [image code] com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:87)
RSP 00007ffe5a23fc00 RIP 0000000000404b69 [image code] com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:156)
RSP 00007ffe5a23fc50 RIP 000000000040bea9 [image code] com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)

[Native image heap boundaries: 
ReadOnly Primitives: 0x7fe893d6c008 .. 0x7fe893f6c1b0
ReadOnly References: 0x7fe893f6c388 .. 0x7fe894030198
Writable Primitives: 0x7fe894031000 .. 0x7fe8940992a8
Writable References: 0x7fe8940992c0 .. 0x7fe8941238d8]


[Heap:
[Young generation: 
[youngSpace:
aligned: 0/0 unaligned: 0/0]]
[Old generation: 
[fromSpace:
aligned: 0/0 unaligned: 0/0]
[toSpace:
aligned: 0/0 unaligned: 0/0]
[pinnedFromSpace:
aligned: 0/0 unaligned: 0/0]
[pinnedToSpace:
aligned: 0/0 unaligned: 0/0]]
[Unused:
aligned: 0/0]]

END RequestId: 2fef123c-f827-11e8-ad2a-13d1ebd52648
REPORT RequestId: 2fef123c-f827-11e8-ad2a-13d1ebd52648	Init Duration: 75.25 ms	Duration: 868.50 ms	Billed Duration: 1000 ms Memory Size: 128 MB	Max Memory Used: 37 MB	
RequestId: 2fef123c-f827-11e8-ad2a-13d1ebd52648 Error: Runtime exited with error: exit status 99
Runtime.ExitError
```

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #841.  This should take care of AWS signal handling problems by using `sem_init` only on platforms conforming to POSIX.2001 and later.

### CODE REVIEW

**Comment by dmlloyd** [comment]
The Travis failure is some Python issue, apparently.

**Comment by vjovanov** [comment]
Yes, this issue is not related to this PR. Running all tests now.

**Comment by vjovanov** [comment]
Thank you greatly for your contribution.

**Comment by drissamri** [comment]
Any idea when this might be released?

**Pull request merged**
