### PR TITLE
Replace jdk8 github gates with jdk17 ones

### PR DESCRIPTION
**Pull request by zakkak**
Complementary to https://github.com/oracle/graal/pull/3967

### CODE REVIEW

**Comment by zakkak** [comment]
@dougxc according to the runs on my fork the only failing gate (and I expect it to fail in this PR's runs as well) is

```
${MX_PATH}/mx --primary-suite-path vm --J @"-Xmx2g" --java-home=${JAVA_HOME} gate --strict-mode --tags build,sulong
```

It fails with:
```
([1/288] Building C object CMakeFiles/interop_interop003.c.dir_toolchain-plain.dir/interop/interop003.c.o
FAILED: CMakeFiles/interop_interop003.c.dir_toolchain-plain.dir/interop/interop003.c.o 
/home/runner/work/mandrel/mandrel/sulong/mxbuild/linux-amd64/SULONG_BOOTSTRAP_TOOLCHAIN/bin/graalvm-native-clang -Dinterop_interop003_c_dir_toolchain_plain_EXPORTS  -g -Wno-unused-function -I/home/runner/work/mandrel/mandrel/sulong/mxbuild/jdk17/SULONG_LEGACY/include -I/home/runner/work/mandrel/mandrel/sdk/mxbuild/linux-amd64/GRAALVM_AD9B45A953_JAVA17/graalvm-ad9b45a953-java17-22.0.0-dev/jre/languages/llvm/include -fPIC -MD -MT CMakeFiles/interop_interop003.c.dir_toolchain-plain.dir/interop/interop003.c.o -MF CMakeFiles/interop_interop003.c.dir_toolchain-plain.dir/interop/interop003.c.o.d -o CMakeFiles/interop_interop003.c.dir_toolchain-plain.dir/interop/interop003.c.o -c /home/runner/work/mandrel/mandrel/sulong/tests/com.oracle.truffle.llvm.tests.interop.native/interop/interop003.c
/home/runner/work/mandrel/mandrel/sulong/tests/com.oracle.truffle.llvm.tests.interop.native/interop/interop003.c:30:10: fatal error: 'graalvm/llvm/polyglot.h' file not found
#include <graalvm/llvm/polyglot.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Since I have no experience at all in building or testing sulong could you please have someone have a look at it?

**Comment by dougxc** [comment]
@rschatz could you please help with this sulong build issue.

**Comment by rschatz** [comment]
Huh... `-I/home/runner/work/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_AD9B45A953_JAVA17/graalvm-ad9b45a953-java17-22.0.0-dev/jre/languages/llvm/include`...

That should be `languages/llvm/include`, not `jre/languages/llvm/include`. I wonder why that doesn't fail in our internal gates. I'll investigate.

**Comment by rschatz** [comment]
That particular job is still at JDK8 internally, I overlooked it because it's in the `vm` suite, not in the `sulong` suite ;)

@pejovica is already working on a fix.

**Comment by pejovica** [comment]
@zakkak I'll integrate this PR together with the fix for the sulong gate.

**Comment by zakkak** [comment]
> @zakkak I'll integrate this PR together with the fix for the sulong gate.

Ack, thanks for the heads up and for taking care of this.

**Pull request merged**
