### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by algonell**
Fix typos in documentation, comments, etc.

### CODE REVIEW

**Comment by algonell** [comment]
Cleanups completed.

**Comment by ezzarghili** [comment]
Please make a PR with 1 commit squashing all your changes, the PR is unreadable

**Comment by ezzarghili** [comment]
@olyagpl you might want to look into these

**Comment by olyagpl** [comment]
Hello @algonell,
We thank you for your time to go over the GraalVM documentation and Java comments! 
What tool did you use to spot all the typos? 
We'll consider accepting this PR and but it would be much easier for us to push these  multiple file changes through CI gates if you split corrections in .md and .java files into 2 separate pull requests.
Olga

**Comment by algonell** [comment]
@olyagpl, my secret sauce is [codespell](https://github.com/codespell-project/codespell/).

Will split, thanks.

**Comment by olyagpl** [comment]
Cool! The other file types should go with .java.

**Pull request closed without merging**
