### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ertugrulcetin**

### CODE REVIEW

**Comment by dougxc** [comment]
I would recommend not using the github UI as it appears to attach a rather unhelpful email address to the commit (see message from graalvmbot above). In any case, for such a minor documentation fix, it's probably easiest to open an issue instead and we can make the change as part of a cleanup in another PR we're already working on.

**Comment by ertugrulcetin** [comment]
So you want me to revert the old PR and delete this one? If so no problem I can do it

**Comment by dougxc** [comment]
No, we can stay with this PR. Do you know how to squash and force push with git to edit history on a branch?

**Comment by ertugrulcetin** [comment]
yeah I do the thing is I was just reading the md and wanted to add this simple change through gui thats all :)

**Comment by dougxc** [comment]
Ok. To save you the hassle, just close this PR and I'll make the update.

**Comment by ertugrulcetin** [comment]
thanks

**Pull request closed without merging**
