### PR TITLE
Parse clang version correctly even when it contains dashes

### PR DESCRIPTION
**Pull request by koutheir**
Parse clang version correctly even when it contains dashes.

### CODE REVIEW

**Comment by koutheir** [comment]
@graalvmbot: I already signed the OCA on 2018-04-03.

**Review by lazar-mitrovic — COMMENTED** [review]
Isn't this code for parsing Intel(R) C++ Compiler version? 
As far as I see clang code is on line 232?

https://github.com/oracle/graal/blob/ec8c73d34531bf2a28fbd92cb72f0886d9d0c9fa/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CCompilerInvoker.java#L223-L233

**Comment by koutheir** [comment]
@lazar-mitrovic That was a merge mistake. Thank you for catching it. I fixed the commit.

**Comment by koutheir** [comment]
Can someone approve running the workflows?

**Comment by koutheir** [comment]
I have no idea what's wrong with the failing CE builds. I don't think these failures are caused by this commit.

**Comment by gilles-duboscq** [comment]
I will take this for integration

**Pull request merged**
