### PR TITLE
Use a more scalable API with less hardcoding for Espresso processors

### PR DESCRIPTION
**Pull request by ivan-ristovic**
This PR refactors Espresso's processors to use more scalable API with less string concatention abusing.

The [diff](https://github.com/oracle/graal/files/7373685/diff.txt) that shows the differences in the generated files prior to and after this refactor contains only whitespace removals/additions where they were not necessary or missing.

### CODE REVIEW

**Comment by oubidar-Abderrahim** [comment]
Thank you for contributing to GraalVM, this PR is tracked internally by GR-34159

**Comment by ivan-ristovic** [comment]
Ofcourse, I have attached it to the main post.

**Comment by ivan-ristovic** [comment]
>  
> I'm good with the changes. This PR gets rid of a technical debt I'm happy to part with.
> 
> If you can fix the checkstyle issues that appear when running `mx checkstyle` (eg: missing copyright headers, etc), along with fixing the warnings when building (eg: not used values), I'll integrate it.

Thanks! 

Style issues fixed. Unused methods within processors removed, though I left some unused methods in the builder API itself, I assume that is OK for the future use cases?

**Comment by rakachan** [comment]
Thank you for the fixes.
From what I see, you have fixed format and style issues, but not yet the compile warning.
My guess is that you are compiling with `javac`. We are using `ecj` to detect these warnings.

This has made me realize that we are not running the style checks gate for Espresso in Github, so I will try to add them soon-ish.

> Unused methods within processors removed, though I left some unused methods in the builder API itself, I assume that is OK for the future use cases?

That is perfectly fine. API methods are public, and usage of public methods is not enforced.

**Comment by ivan-ristovic** [comment]
@rakachan Seems that I forgot to leave a comment, I made the requested changes to this PR and it should be ready for merging now.

**Comment by rakachan** [comment]
@ivan-ristovic I had been working on the merging, and this PR was merged yesterday morning :)
The merge commit is 84329fe379148f65f27e60baca0738851288bf9d
Since the automated process did not trigger here, I will be closing this PR manually if that's alright with you

**Comment by ivan-ristovic** [comment]
Oh, did not notice that. Thanks!

**Pull request closed without merging**
