### PR TITLE
Adding the "Towards a polyglot framework for factorized ML" paper

### PR DESCRIPTION
**Pull request by davidmrdavid**
Hi all, I saw that in [this](https://www.graalvm.org/community/publications/) page that you all accept PRs to include research work done with GraalVM.
I'm sending this PR to include some work that I started during my internship at OracleLabs in the summer of 2019. Thanks!

I also noticed that the publications [page](https://www.graalvm.org/community/publications/) hasn't been updated in some time. Will it be updated again anytime soon with the contents of this README? I noticed that the 2020 papers don't show up, for example. Thanks again!

Also tagging @lukasstadler, who was involved in this work :-)

### CODE REVIEW

**Comment by olyagpl** [comment]
@davidmrdavid, could you please sign the Oracle Contributor Agreement so we could accept your PR?

**Comment by davidmrdavid** [comment]
Thank you all, my apologies for the delay, I've been busy with various things.
@olyagpl , I just signed the OCA under my email, and the site tells me it's currently in review. Please let me know if there's anything else on my end that I need to complete.

Also, as a heads up, the OCA link provided by the bot above leads to a 404 error, which is part of why I took some time in taking action.

**Comment by olyagpl** [comment]
Thanks @davidmrdavid. The academic publications list is being updated including your PR. Thanks for heads up!

**Comment by davidmrdavid** [comment]
Thanks! I also just received an email that the OCA review has been completed. Not sure how to re-start the GitHub oca-bot so that the PR can be reviewed though

**Comment by olyagpl** [comment]
David, publications list is up-to-date.
Thanks for cooperation!

**Pull request merged**
