### PR TITLE
Refactor debuginfo provider

### PR DESCRIPTION
**Pull request by adinn**
This PR fixes the problem mentioned in issue #6990

### CODE REVIEW

**Comment by oubidar-Abderrahim** [comment]
Thank you for contributing to GraalVM.
@olpaw @fniephaus can you please review this PR?

**Comment by olpaw** [comment]
@adinn is this PR created in coordination with the needs for PR https://github.com/oracle/graal/pull/4964 ?

**Comment by adinn** [comment]
> @adinn is this PR created in coordination with the needs for PR https://github.com/oracle/graal/pull/4964 ?

@olpaw @rishikeshdevsot Yes, indeed it is.

**Review by fniephaus — APPROVED** [review]
LGTM

**Comment by fniephaus** [comment]
@oubidar-Abderrahim please start the integration process.

**Review by olpaw — APPROVED** [review]

**Comment by olpaw** [comment]
- [ ] Please fold the style fix commit into the prev. commit.

**Pull request merged**
