### PR TITLE
Fix broken link in substratevm/Resources.md

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
I have sent the signed OCA yesterday. Could you please re-check your records?

**Comment by dmlloyd** [comment]
I believe you're covered under the blanket Red Hat agreement, @ppalaga.

**Comment by ppalaga** [comment]
Thanks, @dmlloyd, I have confirmed with @robilad that my contribution goes under the blanket Red Hat agreement.

**Comment by fniephaus** [comment]
Thanks! This has been fixed a couple of months ago (see [`/docs/reference-manual/native-image/Resources.md`](https://github.com/oracle/graal/blob/12999967bd12d81440b4daa3a7d5101c3424131f/docs/reference-manual/native-image/Resources.md)).

**Pull request closed without merging**
