### PR TITLE
Fix typo in get-started-graalvm-community.md

### PR DESCRIPTION
**Pull request by aben20807**

### CODE REVIEW

**Comment by aben20807** [comment]
@graalvmbot  I've already signed the OCA

**Comment by aben20807** [comment]
@graalvmbot I've already signed the OCA

**Comment by fniephaus** [comment]
Thanks for the PR, @aben20807. I can see your username in the OCA Signatories. Are you sure you used the same email address that you also used to author your commit (see https://github.com/oracle/graal/pull/3577#issuecomment-878732915)?

**Comment by aben20807** [comment]
Hi @fniephaus ,
Yes, I am sure. The `git log` shows below
```text
commit d65e76afe91777e2aec8ca836929cc7ddec2bc7c (HEAD -> patch-1, origin/patch-1)
Author: aben20807 <aben20807@gmail.com>
Date:   Tue Jul 13 10:16:58 2021 +0800

    Fix typo in get-started-graalvm-community.md
```

**Comment by fniephaus** [comment]
Performing another check...

**Review by zakkak — APPROVED** [review]

**Comment by fniephaus** [comment]
Merged via https://github.com/oracle/graal/commit/98ed01b8cf23696fc10e6b6eb8fd0f26e4f98c42.

**Pull request closed without merging**
