### PR TITLE
Fix NPE in coverage when a source has no path

### PR DESCRIPTION
**Pull request by chrisseaton**
Also generally add source name support to coverage.

https://github.com/Shopify/truffleruby/issues/1

### CODE REVIEW

**Comment by eregon** [comment]
Seems related to https://github.com/oracle/graal/pull/1800.
I think it would be useful if @boris-spas reviews both.

**Comment by chrisseaton** [comment]
Yes I think this one is a proper fix, while #1800 is a workaround which could probably be better fixed by doing something else, that's why they're separate.

**Comment by boris-spas** [comment]
Thanks all, I'm aware of this an on it as soon as I can!

**Comment by boris-spas** [comment]
Should be fixed by https://github.com/oracle/graal/commit/531e9b22510fecb992fab857b49581763565cd2f
Thanks!

**Pull request closed without merging**
