### PR TITLE
JDK-8193241: Part 1. Added intrinsic support for (Math) dec/incrementExact

### PR DESCRIPTION
**Pull request by phedlin**
Minimal intrinsic support for Math./dec/inc/rementExact.
(Primarily testing account setup and work-flow.)

### CODE REVIEW

**Comment by eregon** [comment]
Those intrinsics in the pull request might actually decrease performance unless IntegerAddExactNode is smart enough. The pure-Java implementation seems better because it generates a normal floating AddNode and a check against `Integer.MAX_VALUE`.
IntegerAddExactNode on the other hand behaves like a fixed node IIRC, which restricts optimizations.
cc @aardvark179

**Comment by thomaswue** [comment]
@eregon IntegerAddExactNode is a floating node that is only at later stages during compilation lowered into a fixed IntegerAddExactSplitNode.

**Comment by aardvark179** [comment]
I'm not sure if this behaviour has changed since July, but we originally added special cases in TruffleRuby for incrementing fixnums because in tight loops it ultimately generated code like this
```
cmp    r10d,0x7fffffff
je     handler
cmp    r10d,0x7ffffffe
je     handler
...
add    r10d, 0x13
```
rather than
```
add    r13d, 0x1
jo     handler
add    r13d, 0x1
jo     handler
add    r13d, 0x1
jo     handler
...
```
Which can have a large (upto 20x on my machine) performance difference, though ideally we'd see this series of incrementExacts compiled down to something like
```
add    r13d, 0x13
jo     handler
```

**Comment by dougxc** [comment]
@aardvark179 , once this PR is merged, please double check the impact on the code pattern you show above.

**Pull request merged**
