### PR TITLE
[GR-51623] Call `String::to{Upper,Lower}Case` with `Locale.ENGLISH`

### PR DESCRIPTION
**Pull request by petermz**
`String::toUpper/LowerCase` methods use system locale by default. Most of the locales work fine, but some don't, one example is Turkish where `I` and `i` are different letters. This is causing build failures such as https://github.com/oracle/graal/issues/7786 .

I believe it is safer to always pass `Locale.ENGLISH` into these methods. To limit scope of this fix, I only fixed places where errors might occur. I didn't touch user-facing messages, assertions, and tests.

### CODE REVIEW

**Comment by oubidar-Abderrahim** [comment]
Thank you for your contribution to Graal, we'll take a look into this shortly.

**Review by fniephaus — APPROVED** [review]
This LGTM, thanks for the PR!

**Comment by fniephaus** [comment]
Note that I merged this via #8247 and that I also added a test to ensure this doesn't happen again:
https://github.com/oracle/graal/pull/8247/files#diff-ba10d62de621598019c54022b8ce83841a16b60d1e9dd7792e3a396ce0bbc32e

**Comment by petermz** [comment]
Looks great!
Does this kind of test somehow apply automatically to all SubstrateVM
classes?

**Comment by fniephaus** [comment]
> Does this kind of test somehow apply automatically to all SubstrateVM classes?

Yes, we internally run a test based on this also on the SVM code base.

**Pull request merged**
