### PR TITLE
Fix `getCallerClass` methods to acquire the correct frame

### LINKED ISSUE #1479: Access checking fails due to wrong `getCallerClass()` results
I don't know the exact issue but I think `Reflection.getCallerClass()` is (maybe only sometimes) wrong now.  If you look at the stack trace of quarkusio/quarkus#3074, you can see that the result of `Reflection.getCallerClass()` within `Constructor` was `com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl`, which is one frame lower than the class which should have been returned.  I'm thinking it might be a result of oracle/graal@a14d2f1, specifically the factoring out of `StackTraceUtils`. The problem occurs in 19.1.0 but not 19.0.x.

Reference: https://github.com/quarkusio/quarkus/pull/3074

/cc @christianwimmer

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #1479

### CODE REVIEW

**Comment by dmlloyd** [comment]
OK this fix is actually wrong: it does move the frame being checked, but it does so in the wrong direction.  Doing an update.

**Comment by dmlloyd** [comment]
This now fixes the problem seen in https://github.com/quarkusio/quarkus/pull/3074.

**Comment by christianwimmer** [comment]
@dmlloyd Do you have a reduced test case for the Quarkus problem? All test cases of `getCallerClass` that I could come up with pass with the current master version, but fail with this PR.

**Comment by dmlloyd** [comment]
That might be tricky.  I can possibly develop one using `Constructor`.  I think I might also need to research if there is special behavior for `@CallerSensitive` - that tickles my memory for some reason.

**Comment by christianwimmer** [comment]
Actually I take it back, I managed to create a test case. The problem is that we probably do the filtering of `Constructor.newInstance` the wrong way: It needs to be filtered when `getCallerClass` is called from the actual constructor - but not when `Constructor.newInstance` itself calls `getCallerClass`.

I'm working on a fix.

**Comment by christianwimmer** [comment]
Replaced by 506f2f188e732219020af3d82b2ec6a97446109a

**Pull request closed without merging**
