### PR TITLE
Improve substitution conflict error message

### LINKED ISSUE #1715: [native-image] When two substitutions are present the error is not helpful
Currently `register` looks like:

```
   private static <T> void register(Map<T, T> substitutions, T annotated, T original, T target) {
        if (annotated != null) {
            guarantee(!substitutions.containsKey(annotated) || substitutions.get(annotated) == original || substitutions.get(annotated) == target, "Already registered: %s", annotated);
            substitutions.put(annotated, target);
        }
        ...
    }
```

The output message only indicates the substitution is already registered but not what is causing the conflict. This means the only way for the user to find out is to attach a debugger and set a breakpoint at this line.

The error message should include more information about the two substitutions that conflict so that the user can potentially take appropriate action to remove one of them.

### PR DESCRIPTION
**Pull request by Regan-Koopmans**
This PR resolves #1715 

Conflicts encountered in the registration of method substitutions are currently logged without the conflicting value. These changes add this information to the error message such that debugging these errors can be done more effectively.

### CODE REVIEW

**Comment by fniephaus** [comment]
Thanks! This was merged a while ago via https://github.com/oracle/graal/commit/5ced762b1974eef8ec6df7461cf71d3eddb3605d.

**Comment by fniephaus** [comment]
Sorry, I thought this was merged but that's not the case.

**Comment by Regan-Koopmans** [comment]
@fniephaus I have signed the OCA, but this oca-check does not appear to recognise it. Can this be merged?

**Comment by fniephaus** [comment]
@Regan-Koopmans the OCA check passes now... I've pinged the native image team for a quick review, but otherwise this should be good to go. Thanks!

**Review by cstancu — APPROVED** [review]

**Comment by fniephaus** [comment]
Looks like we can get this merged soon, sorry for the delay!

**Comment by fniephaus** [comment]
Merged via https://github.com/oracle/graal/commit/a19006f595b95d6401cb6c0408bc5a5de6058812.

**Pull request closed without merging**
