### PR TITLE
Add examples of -H:IncludeResources command line options

### LINKED ISSUE #626: Support for multiple values in -H:IncludeResources
According to the docs `-H:IncludeResources` is a single regex, and that seems to be the way it works. It's just not very convenient, if you want to include specific sets of resources, from more than one location - the only pattern I found that worked is `.*` so the binary image is enormous when it is finished building. Maybe multiple values could be supported through a comma-separated list (like `-H:IncludeResourceBundles` already supports)?

### PR DESCRIPTION
**Pull request by dsyer**
Fixes #626

### CODE REVIEW

**Comment by dsyer** [comment]
I sent in the OCA. Please check.

**Comment by olpaw** [comment]
@dsyer I added you the the contributors db. Can you rebase and push again so that I see if the  
oca-check succeeds now.

**Comment by olpaw** [comment]
@dsyer so far you are not showing up in http://www.oracle.com/technetwork/community/oca-486395.html
I sent an email to get verification you signed the OCA. Sorry for the inconvenience.

**Comment by olpaw** [comment]
We have provided more sensible docu for `-H:IncludeResources` on our own.
See https://github.com/oracle/graal/blob/master/substratevm/RESOURCES.md

**Pull request closed without merging**
