### PR TITLE
[GR-50385] Include all reflection queries for registered classes

### PR DESCRIPTION
**Pull request by graalvmbot**

### CODE REVIEW

**Comment by zakkak** [comment]
Hi @loicottet, could you please add a description to the PR?

If I am not mistaken this is related to https://github.com/oracle/graal/issues/7753. It also seems to bypass the proposal in https://github.com/oracle/graal/issues/7962, is that correct?

The reason this was opened and merged that fast I assume was to get it in before the [Rampdown Phase One (aka feature freeze)](https://openjdk.org/projects/jdk/23/), but that leaves us with no time to properly test it and seems risky for a change in the defaults (that we don't seem to have a way to revert through an option). Are there any plans on further patches on top of it that would allow us to avoid this new behavior if needed?

cc @maxandersen

**Comment by zakkak** [comment]
> It also seems to bypass the proposal in #7962, is that correct?

Correcting myself. The proposal in #7962 (to add a new way to register classes that will trigger automatic registration of all metadata) seems to have been implemented in https://github.com/oracle/graal/pull/8369 and this PR seems like a follow up.

**Comment by loicottet** [comment]
The description of the PR should have been copied when mirroring, sorry about that. This PR's point is to "flip the switch" on #8369, so that using `"type"` actually registers all reflective queries having no impact on reachability.

**Comment by zakkak** [comment]
> The description of the PR should have been copied when mirroring, sorry about that.

Thanks for the prompt reply @loicottet. It looks like this is broken in general (I see descriptions missing in most if not all recent mirrored PRs), could you please have someone look into it?

**Pull request closed without merging**
