### PR TITLE
Add spin-lock support via Thread.onSpinWait() intrinsic

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
This is probably not the right approach, but it *seems* to work.

**Comment by Peter-B-Kessler** [comment]
Thank you for your contribution to SubstrateVM!

Such a substitution is not appropriate for SubstrateVM, but should instead be handled by the Graal compiler, so that the benefits of `Thread.onSpinWait()` are available to everyone that uses the Graal compiler (including all the SubstrateVM code), not just SubstrateVM developers.

**Comment by dmlloyd** [comment]
Yeah I think this should be done with an intrinsic, or something like that, but I am not really clear on the "right" approach.  I'd be happy to do it "right" though, if only I could understand what that is :)

**Comment by cstancu** [comment]
@dmlloyd this PR should be superseded by https://github.com/oracle/graal/commit/6b20d947094eea9a140ae834dd54e8d5d003427d. Can you please confirm and close this? Thanks!

**Comment by dmlloyd** [comment]
Great! Thanks.

**Pull request closed without merging**
