### PR TITLE
[GR-42108] HeapImplMemoryMXBean set heapMaxSize value

### PR DESCRIPTION
**Pull request by JoeCqupt**
HeapImplMemoryMXBean set heapMaxSize value

### CODE REVIEW

**Comment by JoeCqupt** [comment]
I signed the Oracle Contributor Agreement and it is under review.

**Comment by JoeCqupt** [comment]
@christianhaeubl @christianwimmer  PTAL

**Comment by fniephaus** [comment]
This PR, unfortunately, cannot be merged as the author has withdrawn from the OCA.

**Review by fniephaus — APPROVED** [review]
LGTM, thanks!

**Comment by fniephaus** [comment]
This was merged as part of #5363. Thanks for contributing!

**Pull request closed without merging**
