### PR TITLE
Runtime initialize JDK class com.sun.jndi.ldap.ServiceLocator

### LINKED ISSUE #3297: native-image on applications using com.sun.jndi.ldap.ServiceLocator fail
**Describe the issue**
https://github.com/oracle/graal/commit/11b9817fb341f9447c300304fe461933bf79c2aa#diff-8ea159555f76609d835155ca3b7f534b8a5adbb932fa6366c4db09a5b2ec2275R62 banned Random/SplittableRandom from the image heap. As it turns out there is still some usage of `java.util.Random` in `com.sun.jndi.ldap.ServiceLocator` (part of OpenJDK 11), which isn't properly configured to get runtime-reinitialized. That's unlike other usages within OpenJDK.

**Steps to reproduce the issue**
Run the quarkus elytron-security-ldap integration tests with `-Dnative`

**Describe GraalVM and your environment:**
 - GraalVM version: master, revision e1eb501fe3106ddddbe6a5dbc08db866663b1976
 - JDK major version: **11**
 - OS: **Linux**
 - Architecture: **AMD64**

**More details**
Stack trace looks like this:
```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.sun.jndi.ldap.ServiceLocator class initializer with a trace: 
 	at java.util.Random.<init>(Random.java:105)
	at com.sun.jndi.ldap.ServiceLocator.<clinit>(ServiceLocator.java:47)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: 
	at parsing java.naming@11.0.11-ea/com.sun.jndi.ldap.ServiceLocator.selectHostport(ServiceLocator.java:248)
Call path from entry point to com.sun.jndi.ldap.ServiceLocator.selectHostport(ServiceLocator$SrvRecord[], int, int): 
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.ServiceLocator.selectHostport(ServiceLocator.java:232)
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.ServiceLocator.extractHostports(ServiceLocator.java:220)
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.ServiceLocator.getLdapService(ServiceLocator.java:185)
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.ServiceLocator.getLdapService(ServiceLocator.java:114)
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.DefaultLdapDnsProvider.lookupEndpoints(DefaultLdapDnsProvider.java:59)
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:200)
	at com.oracle.svm.reflect.LdapCtxFactory_getUsingURL_3f8afafe7f27d6a3ad324737dd5b4a503b392567_210.invoke(Unknown Source)
	at java.base@11.0.11-ea/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base@11.0.11-ea/java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:737)
	at java.base@11.0.11-ea/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:720)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:217)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:170)
	at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:291)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
```

### PR DESCRIPTION
**Pull request by jerboaa**
This class uses java.util.Random for selecting a service record
at random in selectHostport()

Closes #3297

### CODE REVIEW

**Comment by jerboaa** [comment]
Pretty straight-forward fix :)

**Comment by jerboaa** [comment]
@dougxc Could you please help review this? It helps the #3272 story too :smile: Thank you!

**Comment by vjovanov** [comment]
I fused this with another PR where we changed the JDK feature. Should be merged soon.

Thanks!

**Comment by jerboaa** [comment]
@vjovanov OK, thanks!

**Comment by jerboaa** [comment]
@vjovanov Gentle ping.

**Comment by dougxc** [comment]
Can this now be closed @vjovanov ?

**Comment by maxandersen** [comment]
> I fused this with another PR where we changed the JDK feature. Should be merged soon.

which PR was this ?

**Comment by zakkak** [comment]
It looks like this has not been merged yet (21.2.0-dev 7b97b5c)
I see:
```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  To see how this object got instantiated use --trace-object-instantiation=java.util.Random. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: 
	at parsing java.naming@11.0.11/com.sun.jndi.ldap.ServiceLocator.selectHostport(ServiceLocator.java:248)
Call path from entry point to com.sun.jndi.ldap.ServiceLocator.selectHostport(ServiceLocator$SrvRecord[], int, int): 
	at java.naming@11.0.11/com.sun.jndi.ldap.ServiceLocator.selectHostport(ServiceLocator.java:232)
	at java.naming@11.0.11/com.sun.jndi.ldap.ServiceLocator.extractHostports(ServiceLocator.java:220)
	at java.naming@11.0.11/com.sun.jndi.ldap.ServiceLocator.getLdapService(ServiceLocator.java:185)
	at java.naming@11.0.11/com.sun.jndi.ldap.ServiceLocator.getLdapService(ServiceLocator.java:114)
	at java.naming@11.0.11/com.sun.jndi.ldap.DefaultLdapDnsProvider.lookupEndpoints(DefaultLdapDnsProvider.java:59)
	at java.naming@11.0.11/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:200)
	at com.oracle.svm.reflect.LdapCtxFactory_getUsingURL_3f8afafe7f27d6a3ad324737dd5b4a503b392567_215.invoke(Unknown Source)
	at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base@11.0.11/java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:737)
	at java.base@11.0.11/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:720)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
	at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:291)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
```
in https://github.com/zakkak/mandrel/runs/2404107524?check_suite_focus=true

**Comment by vjovanov** [comment]
Not merged yet on master. It will come out with 21.1 release, and it will be merged early next week on master.

**Comment by zakkak** [comment]
Hi @vjovanov are there any updates on this?

**Comment by jerboaa** [comment]
@vjovanov Any update? Has this been merged now? If yes, which commit?

**Comment by zakkak** [comment]
This is now merged.
commit: https://github.com/oracle/graal/commit/159326351f354105f7fa5f347b97484c6a436456

**Comment by vjovanov** [comment]
Sorry for the delay. It got bounced many times in the CI for various reasons.

**Comment by jerboaa** [comment]
Thank you!

**Pull request closed without merging**
