### PR TITLE
[GR-39370] Fall back to older JVMCI API when HotSpotJDKReflection is not available

### LINKED ISSUE #4655: [GR-39370] Graal master not building (Mandrel distribution) with upstream OpenJDK 11 builds
**Describe the issue**
https://github.com/oracle/graal/pull/4614 introduces an unconditional dependency on `jdk.vm.ci.hotspot.HotSpotJDKReflection` and `jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getReflection()` which are not available in OpenJDK 11.

Both dependencies were introduced by https://bugs.openjdk.org/browse/JDK-8220623 which has not been backported to upstream OpenJDK 11, thus breaking Mandrel builds which are based on upstream OpenJDK 11 builds.

**Steps to reproduce the issue**
```
git clone git@github.com:graalvm/mandrel-packaging.git
cd mandrel-packaging
export JAVA_HOME=path/to/java
$JAVA_HOME/bin/java -ea build.java --mx-home path/to/mx --mandrel-repo path/to/graal
```

**Describe GraalVM and your environment:**
 - GraalVM version: **99228369a8c126210307145110e38a43847259a6**
 - JDK major version: **OpenJDK 11.0.16+7**
 - OS: **Fedora 36**
 - Architecture: **AMD64**
 
 **More Details:**
 
 The build fails with:
 
 ```
 Building com.oracle.svm.native.jvm.posix_amd64 with Ninja... [dependency svm-jvmfuncs-fallback-builder updated]
Fatal error: com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchMethodException: jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getReflection()
	at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:82)
	at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:69)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.<clinit>(SubstrateAnnotationExtracter.java:118)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport.<init>(NativeImageClassLoaderSupport.java:157)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:180)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:123)
Caused by: java.lang.NoSuchMethodException: jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getReflection()
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:74)
	... 5 more
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1678)
	at build.buildAgents(build.java:227)
	at build.main(build.java:209)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1663)
	at build.buildAgents(build.java:227)
	at build.main(build.java:209)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by zakkak**
Closes #4655

### CODE REVIEW

**Comment by loicottet** [comment]
Thank you for this! I had started working on a fix with pretty much the same idea as what you've done. I assume that the tests are passing on your side since the PR is no longer marked as draft, and I can merge those changes as is?

**Review by loicottet — APPROVED** [review]

**Review by jerboaa — COMMENTED** [review]
This looks OK to me. Are there tests for `SubstrateAnnotationExtractor` that can can be run? I.e. how can we be sure to not have introduced a regression for Mandrel JDK 11?

**Comment by zakkak** [comment]
> Thank you for this! I had started working on a fix with pretty much the same idea as what you've done.

Sorry for not self-assigning the issue to myself the moment I started working on it. Nice to see that my approach ended up similar to yours :)

> I assume that the tests are passing on your side since the PR is no longer marked as draft, and I can merge those changes as is?

Correct, the tests are passing on our side. Note however that I am not sure whether these changes result in `getRoot` always returning the same `AnnotatedElement` for a given parameter, but I am confident enough that it does so. In any case even if it doesn't AFAIU it would only slightly affect performance but not correctness.

>  Are there tests for SubstrateAnnotationExtractor that can can be run?

AFAIK no, there are no such tests. @loicottet might know better though.

> I.e. how can we be sure to not have introduced a regression for Mandrel JDK 11?

Other than our existing tests passing I think we don't have any other way to be sure at the moment. 

This PR could potentially introduce two kinds of regressions:

1. Returning different annotations when using OpenJDK 11 versus when using LabsJDK 11
2. Initializing referenced classes/interfaces essentially reverting the changes of https://github.com/oracle/graal/pull/4614

For 2 I feel pretty confident that it is not happening since we are still not using `getAnnotations` directly and we go through the `GuardedAnnotationAccess`. 

To be sure we need to craft new tests for `SubstrateAnnotationExtractor` and `GuardedAnnotationAccess`, I feel familiar enough with this code to think of enough complex cases to test though. @loicottet do you think you could help on that side? e.g. by providing a high-level description of interesting cases we could test.

**Comment by loicottet** [comment]
> Correct, the tests are passing on our side. Note however that I am not sure whether these changes result in getRoot always returning the same AnnotatedElement for a given parameter, but I am confident enough that it does so. In any case even if it doesn't AFAIU it would only slightly affect performance but not correctness.

The returned `AnnotatedElement` will be the same since it can only return the underlying `Class`, `Method`, `Constructor` or `Field`, which is unique (in all cases except `Class`, the objects are not actually unique, however they are all pairwise equal and contain the same annotation data, so they effectively look like the same object to the annotation parsing code).

> This PR could potentially introduce two kinds of regressions:
> 1. Returning different annotations when using OpenJDK 11 versus when using LabsJDK 11
> 2. Initializing referenced classes/interfaces essentially reverting the changes of https://github.com/oracle/graal/pull/4614

I am pretty confident that none of those could happen, the first one because of what I wrote above, and the second one since the annotations are only initialised on a call to `getAnnotations` or a similar method, which indeed doesn't happen in that case.

> To be sure we need to craft new tests for SubstrateAnnotationExtractor and GuardedAnnotationAccess, I don't feel familiar enough with this code to think of enough complex cases to test though. @loicottet do you think you could help on that side? e.g. by providing a high-level description of interesting cases we could test.

I think simply testing whether an annotation class that is marked for run-time initialisation is indeed not initialised at build-time would be sufficient, since all image classes have their annotations parsed in the image class loader during the Native Image builder startup.

**Comment by jerboaa** [comment]
Pushed with https://github.com/oracle/graal/commit/3fccbac3fc0681e3d3a71b3582907208262d111c

**Comment by zakkak** [comment]
Hi @loicottet , can you please confirm that this is also getting backported to the 22.2 release branch? Thanks

**Comment by zakkak** [comment]
Backported with ea42fa7f86bcdc9e388e6b0205f3d4420140c9eb. Thank you @loicottet !

**Pull request closed without merging**
