### PR TITLE
CI: Use docker image for Elasticsearch ITs

### LINKED ISSUE #2782: [Quarkus-CI] JVMCI Compiler does not support selected GC: concurrent mark sweep gc
**Describe the issue**
#2143 now appears [in graal's new quarkus workflow](https://github.com/oracle/graal/blob/master/.github/workflows/quarkus.yml).
See https://github.com/oracle/graal/runs/1019872072?check_suite_focus=true#step:17:295

[Looking for `UseConcMarkSweepGC` in the quarkus repository](https://github.com/quarkusio/quarkus/search?q=UseConcMarkSweepGC&unscoped_q=UseConcMarkSweepGC) we see that the three `elasticsearch` tests use it. 

In graal's quarkus workflow we use GraalVM as the `JAVA_HOME`
https://github.com/oracle/graal/blob/e1c07f83fdf953de97b87461c4bb1855b3e2eb3e/.github/workflows/quarkus.yml#L360
thus breaking those `elasticsearch` tests.

Elasticsearch seems to support G1GC for java > 11, but Quarkus has not abandoned java 8 support yet so it appears like it can't do the switch yet.

### PR DESCRIPTION
**Pull request by zakkak**
Changes are picked from https://github.com/quarkusio/quarkus/pull/11599

Closes #2782

### CODE REVIEW

**Comment by zakkak** [comment]
Leaving it as draft till Quarkus 1.8.0 release, since it doesn't work with the current release.

**Comment by zakkak** [comment]
Quarkus 1.8.0 is now released, could someone trigger a re-run of the action please?

**Comment by zakkak** [comment]
Thanks to whoever did the re-run :)
The failing test group was Data 6 and it looks fine now https://github.com/oracle/graal/pull/2797/checks?check_run_id=1118210794

**Comment by zakkak** [comment]
Hi @dougxc, can we please get this merged?

**Comment by dougxc** [comment]
Yes. @sanzinger will merge it as part of another PR that will be merging soon.

**Comment by zakkak** [comment]
Hello @sanzinger, do you have any updates on this?

**Comment by sanzinger** [comment]
Looks good. I'm going to merge this PR.

**Pull request merged**
