### PR TITLE
Adjust the regexp to allow AdoptOpenJDK.

### PR DESCRIPTION
**Pull request by bobmcwhirter**

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Seems this will get subsumed by parallel work by @gilles-duboscq

**Comment by gilles-duboscq** [comment]
Hey sorry Bob i didn't see your PR

**Comment by bobmcwhirter** [comment]
btw, I rebased this upon your changes. Seems to still be required for AdoptOpenJDK matching.

Prior to this commit, master as of Right Now says:

```
'/Users/bob/graalvm/jdk-11.0.3+7/Contents/Home' has an unexpected version string:
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
does not match:
(openjdk|java) version \"(?P<jvm_version>[0-9a-z_\-.]+)\".*\n(OpenJDK|Java\(TM\) SE) Runtime Environment [ 0-9.]*\(build [0-9a-zA-Z_\-.+]+\)
```

Thus, I'll leave this PR open for review/merge, please.

**Comment by gilles-duboscq** [comment]
My changes are not yet on master.
They are in the pipeline and should be pushed to `master` soon.

**Comment by gilles-duboscq** [comment]
The fix for #1304 is now in master.
I checked locally that it works so i'm closing this. Please re-open if it still doesn't work for you.

**Pull request closed without merging**
