### PR TITLE
Fix getAndAddInt() to take an Allocatable delta

### PR DESCRIPTION
**Pull request by daniel-stewart-qdt**
Fix for the getAndAddInt() function to take an AllocatableValue.

### CODE REVIEW

**Comment by daniel-stewart-qdt** [comment]
Not sure I understand the failures. It seems like maybe the JDK11 requirement is not getting met? Is there something I need to change in order to find the right JDK?

**Comment by sanzinger** [comment]
I am currently integrating this fix.

**Comment by dougxc** [comment]
Did you see my comment above @sanzinger on the fix needed for the Travis failure?

**Comment by daniel-stewart-qdt** [comment]
I did. I assume that is still needed even though @sanzinger is integrating?

**Comment by dougxc** [comment]
I've canceled the integration so that you can push the change I suggested to ensure it fixes the Travis issue.

**Comment by sanzinger** [comment]
Thank you for reminding me on this. I'll add it.

**Comment by sanzinger** [comment]
Ok, now it seems to be clear.

**Comment by sanzinger** [comment]
Wow, I was even able to update the branch in your repository fork.

**Pull request merged**
