### PR TITLE
allowMapAccess and dot notation for hashmaps feature implementation

### PR DESCRIPTION
**Pull request by firatkucuk**
I have created a basic implementation for https://github.com/oracle/graaljs/issues/143 issue, I am pretty sure lots of things are missing. If you guide me. I can handle it in a short period of time.

I have tested with the following code, after PR merged I can put it into the graaljs repository.

```java
@Test
public void allowMapAccessTest() {

    final HostAccess hostAccess = HostAccess.newBuilder().allowAccessAnnotatedBy(HostAccess.Export.class).allowMapAccess(true).build();

    try (final Context context = newContextBuilder().allowHostAccess(hostAccess).build()) {
        final Value bindings = context.getBindings(JavaScriptLanguage.ID);

        bindings.putMember("map", Map.of("one", 1, "x", Map.of("y", 2)));
        assert Integer.valueOf(1).equals(context.eval(JavaScriptLanguage.ID, "map.one").asInt());
        assert Integer.valueOf(1).equals(context.eval(JavaScriptLanguage.ID, "map['one']").asInt());
        assert Integer.valueOf(2).equals(context.eval(JavaScriptLanguage.ID, "map.x.y").asInt());
        assert Integer.valueOf(2).equals(context.eval(JavaScriptLanguage.ID, "map['x']['y']").asInt());
        assert Integer.valueOf(1).equals(context.eval(JavaScriptLanguage.ID, "map.get('one')").asInt());
        assert Integer.valueOf(1).equals(context.eval(JavaScriptLanguage.ID, "var myGet = map.get; myGet('one')").asInt());
        assert Boolean.TRUE.equals(context.eval(JavaScriptLanguage.ID, "map.one === 1").asBoolean());
    }
}
```

### CODE REVIEW

**Comment by firatkucuk** [comment]
I've signed the oca

**Comment by firatkucuk** [comment]
Somehow If I manage to access the `allowMapAccess` configuration from `InteropLibrary`, I'll move the implementation there.

**Comment by firatkucuk** [comment]
@chumer  pipelines fail because Map is blacklisted. List is whitelisted, I need some guidance I can create a workaround but do you have a suggestion?

**Comment by woess** [comment]
Thanks for your contribution. This PR is now obsolete since support for this has already been added.

**Pull request closed without merging**
