### PR TITLE
[Docs] native-image usage docs updated for --static option

### PR DESCRIPTION
**Pull request by neomatrix369**
substrateVM: Added some more docs around the --static option, to make it clearer what is and isn't supported by native-image

Built a tested locally using the below commands in the `substratevm` folder:

```bash
${MX} build && ${MX} native-image --help 
```

`--static` option when `native-image --help` was invoked previously read:

```
    --static              build statically linked executable (requires static libc and zlib)

```

Currently reads:
```
    --static              build statically linked executable (at the moment includes static
                          libc and zlib only, hence requires them both. At the moment only
                          supports Linux).
```

Happy to change it to any other test to convey the same meaning of the message.

This came about post conversations in these issues:
- https://github.com/oracle/graal/issues/827#issuecomment-520150665
- https://github.com/oracle/graal/issues/1600

### CODE REVIEW

**Comment by neomatrix369** [comment]
@olpaw Any progress with this PR?

**Comment by olpaw** [comment]
I'd prefer to have the specifics of `--static` (and it's limitations) to be documented on https://www.graalvm.org/docs/reference-manual/native-image/
cc @olyagpl

**Comment by neomatrix369** [comment]
> I'd prefer to have the specifics of `--static` (and it's limitations) to be documented on https://www.graalvm.org/docs/reference-manual/native-image/
> cc @olyagpl

Is this area available to change via a pull request?

**Comment by olyagpl** [comment]
@neomatrix369 ,  website update process is close but not similar.
I'll take care of graalvm.org. Thank you for pointing at missing information!

**Pull request closed without merging**
