### PR TITLE
Use -1 as max value for eden and survivor spaces

### PR DESCRIPTION
**Pull request by petermz**
This PR addresses #6814.

It turns out max eden size is enforced post factum, i.e. if 'memory used' >= 'max size' then GC is started (see [`AbstractCollectionPolicy::shouldCollectOnAllocation`](https://github.com/oracle/graal/blob/8b81a03fee458013b8b703e234e77edc4836be43/substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/AbstractCollectionPolicy.java#L90)). This applies also to young generation as a whole -- see [`BasicPolicy::shouldCollectOnAllocation`](https://github.com/oracle/graal/blob/8b81a03fee458013b8b703e234e77edc4836be43/substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/BasicCollectionPolicies.java#L60). So we cannot assume that maximum size, as reported by collection policy, will never be exceeded. It seems there is no meaningful estimation for the maximum size of young generation spaces, other than `MaxHeapSize`.

The solution proposed here is to return -1 for young gen (eden and survivor) spaces. This is also how Hotspot behaves in JDKs 17 and 19.

### CODE REVIEW

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for contributing to GraalVM, could you please specify the following

- Is your PR ready for review?
- Is there a specific engineer from the GraalVM team that you want to review this PR? (because he has more context or you discussed these changes with them previously)

**Comment by petermz** [comment]
It's ready for review; as for the reviewer, I don't have any preference.

**Comment by christianhaeubl** [comment]
Thanks for the PR. For eden, this change makes sense.
Why is it necessary to use `UNDEFINED` for the survivor space?

**Comment by petermz** [comment]
Currently `CollectionPolicy.getMaximumSurvivorSize()` is used. Apparently this method isn't called anywhere else, so I felt it was unsafe to rely on.

Furthermore, I now can reproduce this issue with old gen bean as well. This makes sense because `OldGeneration` does no size checks upon adding new chunks (see e.g. `requestAlignedChunk`, or `promoteUnalignedObject`), so it may grow beyond what the policy thinks its max size is.

And it seems `CollectionPolicy.getMaximumHeapSize()` is unsafe too, as it may as well be temporarily exceeded -- see e.g. check in `GCImpl.doCollectOnce`. So I guess all the beans should better return -1 for max size.

**Comment by joggeli34** [comment]
This would really help us, as this blocks us from updating to the newest graalvm, as creates a lot of exceptions.

**Comment by manofthepeace** [comment]
@joggeli34 if you use something like quarkus you can alleviate the issue this way. Not perfect but...

```java
    @Produces
    @Singleton
    // TODO remove once https://github.com/oracle/graal/issues/6814 is fixed and released
    public MeterFilter removeJvmUsed() {
        return MeterFilter.denyNameStartsWith("jvm.memory");
    }
```

**Comment by christianhaeubl** [comment]
Thanks, I will try to get this PR merged.

**Pull request merged**
