### PR TITLE
Fix broken links to document on build configuration

### PR DESCRIPTION
**Pull request by deining**
Please note that this PR is a superset of #3002, which reports the broken link in one file only.

### CODE REVIEW

**Comment by deining** [comment]
Meanwhile, Oracle Contributor Agreement was signed and remitted for acceptance.

**Comment by olpaw** [comment]
> Meanwhile, Oracle Contributor Agreement was signed and remitted for acceptance.

Thanks. Once you show up in https://www.oracle.com/technical-resources/oracle-contributor-agreement.html we can add you to the allowed-list.

**Comment by deining** [comment]
I just received an email that my OCA has been processed, and my name now appears on the OCA signatories page.

**Comment by olyagpl** [comment]
Andreas, the fix was merged. Thanks for your contribution!

**Pull request merged**
