### PR TITLE
Experimental native-image module support

### PR DESCRIPTION
**Pull request by olpaw**

### CODE REVIEW

**Comment by zakkak** [comment]
Hi @olpaw I wanted to give this a go with `--no-jlinking` and it looks like it fails to build:
```
~/code/mx/mx -v --primary-suite-path substratevm --no-jlinking --components='Native Image' build
...
Archiving GRAALJDK_CE_6416F73897_JAVA11... [dependencies updated: GRAAL, GRAAL_MANAGEMENT, GRAAL_PROCESSOR, GRAAL_TRUFFLE_JFR_IMPL, graalvm-jimage]
Process Process-310:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zakkak/code/mx/mx.py", line 14074, in executeTask
    task.execute()
  File "/home/zakkak/code/mx/mx.py", line 4932, in execute
    _built = self.build()
  File "/tmp/graal/sdk/mx.sdk/mx_sdk_vm_impl.py", line 977, in build
    super(GraalVmLayoutDistributionTask, self).build()
  File "/tmp/graal/sdk/mx.sdk/mx_sdk_vm_impl.py", line 833, in build
    super(BaseGraalVmLayoutDistributionTask, self).build()
  File "/home/zakkak/code/mx/mx.py", line 5284, in build
    self.subject.make_archive()
  File "/home/zakkak/code/mx/mx.py", line 6085, in make_archive
    self._install_source(source, output, destination, arc)
  File "/home/zakkak/code/mx/mx.py", line 5878, in _install_source
    ), include=source['path'], excludes=source.get('exclude'), optional=source['optional'])
  File "/home/zakkak/code/mx/mx.py", line 5851, in _install_source_files
    merge_recursive(_source_file, _dst, _arcname, excludes, archive=archive)
  File "/home/zakkak/code/mx/mx.py", line 5819, in merge_recursive
    archiver.add(src, dst, provenance)
  File "/home/zakkak/code/mx/mx.py", line 14670, in add
    self._add_f(filename, archive_name, provenance)
  File "/home/zakkak/code/mx/mx.py", line 14598, in _add_tar
    self.zf.add(filename, archive_name, filter=self._tarinfo_filter, recursive=False)
  File "/usr/lib64/python2.7/tarfile.py", line 2011, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib64/python2.7/tarfile.py", line 1883, in gettarinfo
    statres = os.lstat(name)
OSError: [Errno 2] No such file or directory: '/tmp/graal/sdk/mxbuild/linux-amd64/graalvm-jimage/legal/jdk.net/labsjdk-ce-11.0.10-jvmci-21.1-b01./java.base/LICENSE'
Archiving GRAALJDK_CE_6416F73897_JAVA11 failed
```

**Comment by zakkak** [comment]
This PR looks like a cleanup/rebase of https://github.com/oracle/graal/pull/2372 which got merged a couple of hours ago.

`--no-jlinking` works fine with the latest `master` in combination with the latest Labs OpenJDK 11 (21.1-b02).

**Comment by olpaw** [comment]
Merged as e734181

**Comment by olpaw** [comment]
> `--no-jlinking` works fine with the latest `master` in combination with the latest Labs OpenJDK 11 (21.1-b02).

Glad I didn't brake it. Thanks for checking, @zakkak

**Pull request closed without merging**
