### PR TITLE
Windows debug information prototype

### PR DESCRIPTION
**Pull request by stooke**
This PR is for an initial implementation of debug support for Graal on Windows.  At this stage I submit it more for discussion before I go much further down this road.  

The patch allows Graal to emit CodeView 4 records into windows .obj files, which the windows linker then moves to PDB files at link time.  Visual Studio can then open the executable, breakpoints can be set, and single-steping, etc. will work.

Variables, and type information are not currently supported, and there is limited support for stack frames.

I work closely with Andrew Dinn @adinn on debug support, so my code makes use of his previous work; I duplicate some of the shared classes from his PR here.

There are some differences in how I approach line information, but these are currently compile-time switches.  For more details, please see DEBUGINFO_WINDOWS.md.

### CODE REVIEW

**Comment by olpaw** [comment]
@pejovica please take a look at the Windows specific part of the debug support implementation.
@stooke please rebase your PR onto https://github.com/adinn/graal/tree/debug_info_prototype so that the changes that add Windows support can be reasonably reviewed in this PR. cc @adinn

**Comment by olpaw** [comment]
Since @adinn s PR is on master you will have to rebase your PR against latest master (i.e. rebase https://github.com/stooke/graal/tree/pr_debug_pecoff_prototype to https://github.com/oracle/graal/)
Sorry for the inconvenience.

**Comment by stooke** [comment]
> Since @adinn s PR is on master you will have to rebase your PR against latest master (i.e. rebase https://github.com/stooke/graal/tree/pr_debug_pecoff_prototype to https://github.com/oracle/graal/)
> Sorry for the inconvenience.

A full rebase is not going well - too many conflicts (this could be my inexperience with rebase).  It would be more expedient for me to open a new PR using a repo cloned directly from github/oracle instead of github/adinn.  Is that okay?

**Comment by olpaw** [comment]
>  It would be more expedient for me to open a new PR using a repo cloned directly from github/oracle instead of github/adinn. Is that okay?

Whatever works best for you is fine with us.

**Comment by stooke** [comment]
I have created PR #2396 to replace this, with a properly rebased and cleaned up commit history.

**Pull request closed without merging**
