### PR TITLE
fix bugs related to reading through incomplete phis during parsing (#1690)

### PR DESCRIPTION
**Pull request by dougxc**

### CODE REVIEW

**Comment by kuaiwei** [comment]
BytecodeParser and FrameStateBuilder also use originalValue to check unbalanced monitor. Do we need fix these code?

**Comment by dougxc** [comment]
Yes, we're also looking at those and will add further commits to this PR.

**Comment by kuaiwei** [comment]
Hi Doug,
  I'm wondering when this patch can be merged into graal. We hit this issue in our production environment. I'm wondering when this patch can be merged.

Thanks

**Comment by dougxc** [comment]
Hi @kuaiwei , it's currently going through internal review. The patch has become a little more complex to deal with all the uses of `GraphUtil.originalValue` correctly. I hope to merge it in the next 2 days.

**Comment by dougxc** [comment]
Resolved by https://github.com/oracle/graal/commit/56e35c225709cb2564133eacf3d17bdd1f95ad90

**Pull request closed without merging**
