### PR TITLE
Only add nashorn check on JDK 14 or earlier

### LINKED ISSUE #2365: [OpenJDK 15] Removal of nashorn javascript engine breaks build
In jdk/jdk the nashorn javascript has been removed:
https://openjdk.java.net/jeps/372
https://bugs.openjdk.java.net/browse/JDK-8241749

This breaks the graal VM native image build like this:

```
/home/jenkins/workspace/jdk-15-gaovm-x86-64_linux/src/graal/graal-ce/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_nashorn_api_scripting_NashornScriptEngineFactory.java:33: error: package jdk.nashorn.api.scripting does not exist
import jdk.nashorn.api.scripting.ClassFilter;
                                ^
/home/jenkins/workspace/jdk-15-gaovm-x86-64_linux/src/graal/graal-ce/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_nashorn_api_scripting_NashornScriptEngineFactory.java:45: error: cannot find symbol
    private ScriptEngine newEngine(String[] args, ClassLoader appLoader, ClassFilter classFilter) {
                                                                         ^
  symbol:   class ClassFilter
  location: class Target_jdk_nashorn_api_scripting_NashornScriptEngineFactory
/home/jenkins/workspace/jdk-15-gaovm-x86-64_linux/src/graal/graal-ce/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_nashorn_api_scripting_NashornScriptEngineFactory.java:35: error: package jdk.nashorn.api.scripting does not exist
@TargetClass(jdk.nashorn.api.scripting.NashornScriptEngineFactory.class)
                                      ^
3 errors

WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.jpackage
Compiling com.oracle.svm.core with javac-daemon(JDK 15) failed
1 build tasks failed
```

Substrate VM needs to get updated to account for this. I hope to get a fix in for this later in the week.

/cc @bobvandette

### PR DESCRIPTION
**Pull request by jerboaa**
JDK 15 removed nashorn with:
https://bugs.openjdk.java.net/browse/JDK-8241749

Closes #2365

### CODE REVIEW

**Comment by bobvandette** [comment]
I added your fix to my pull request, https://github.com/oracle/graal/pull/2455, since I need this fix to test.  Hope you don't mind.

**Comment by jerboaa** [comment]
@bobvandette sure. That's fine.

**Comment by jerboaa** [comment]
Shall I close this?

**Comment by bobvandette** [comment]
Lets see if it closes automatically one my PR gets integrated.

**Pull request closed without merging**
