### PR TITLE
RFC: Allow vm/ build to be attempted with JDK11. 

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Strawman implementation of the `mx` build for JDK11-based distributions.

This does *not* accomodate any runtime changes involving modules or classpaths etc.

It mostly focuses around:

* The lack of a `jre/` dir in the JDK11 distributions
* The required `--module-path` and `--upgrade-module-path` and `-XX` options for the launcher scripts
* The required `-J` variants of the above when native-imaging things from the `mx` scripts.

It does not yet:

* Handle any runtime changes
* Adjust the windows launcher script
* Install graal related modules into the `jmods/` directory of the distribution.

Additionally, `polyglot` and `libpolyglot` current fail, thus to experiment, within the `vm11` directory:

    mx clean && mx  --disable-libpolyglot --disable-polyglot --dynamicimports /substratevm build

The resulting distribution does get created a native-image'd `native-image` that will run with at least `--help` on OSX.

A runnable binary is created for `aarch64` but it segfaults when executed due to probably heap-base math issues around copying byte buffers during initialization.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Can anyone provide insight on how this is supposed to work?

https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/ThreadLocalAllocation.java#L221-L260

Under JDK11, when attempting to native-image the polyglot launchers, it's hitting:

    ThreadLocalAllocation::slowPathNewArrayWithoutAllocating(...)

Which is annotated with:

        @RestrictHeapAccess(access = RestrictHeapAccess.Access.NO_ALLOCATION, reason = "Must not allocation in the implementation of allocation.")

Which seems to make sense, other than the fact it pretty immediately calls

        static Object allocateNewArray(DynamicHub hub, int length, ThreadLocalAllocation.Descriptor tlab, boolean rememberedSet) {

Which quickly hits the assertion/check/exit I'm seeing:

            HeapImpl.exitIfAllocationDisallowed("Heap.allocateNewArray", DynamicHub.toClass(hub).getName());

I feel like there's just something I'm missing which should be disabling that check if it's inside an allocation already, or something, maybe.

@sanzinger or @theRealAph ?

**Comment by dougxc** [comment]
Do you have a stack trace for the failure? There must be something *further up the stack* doing an allocation with `new` (as opposed to being in the code that *implements* allocation).

**Comment by bobmcwhirter** [comment]
Here's what I've got:

```
Error: @RestrictHeapAccess warning: Restricted method: 'ThreadLocalAllocation.slowPathNewArrayWithoutAllocating(Class, int)' calls 'CleanerImpl$PhantomCleanableRef.get()' that violates restriction NO_ALLOCATION.
  [Path:
    app//com.oracle.svm.core.genscavenge.ThreadLocalAllocation.slowPathNewArrayWithoutAllocating(ThreadLocalAllocation.java:224)
    app//com.oracle.svm.core.genscavenge.ThreadLocalAllocation.allocateNewArray(ThreadLocalAllocation.java:233)
    app//com.oracle.svm.core.genscavenge.HeapImpl.exitIfAllocationDisallowed(HeapImpl.java:293)
    app//com.oracle.svm.core.heap.NoAllocationVerifier.exit(NoAllocationVerifier.java:61)
    app//com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.shouldNotReachHere(VMErrorSubstitutions.java:59)
    app//com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.shouldNotReachHere(VMErrorSubstitutions.java:74)
    app//com.oracle.svm.core.jdk.VMErrorSubstitutions.shutdown(VMErrorSubstitutions.java:112)
    app//com.oracle.svm.core.jdk.VMErrorSubstitutions.doShutdown(VMErrorSubstitutions.java:150)
    app//com.oracle.svm.core.SubstrateUtil.printDiagnostics(SubstrateUtil.java:270)
    app//com.oracle.svm.core.SubstrateUtil.dumpRuntimeCompilation(SubstrateUtil.java:424)
    app//com.oracle.svm.core.SubstrateUtil.dumpRuntimeCodeCacheTable(SubstrateUtil.java:445)
    app//com.oracle.svm.core.code.RuntimeCodeInfo.logTable(RuntimeCodeInfo.java:329)
    app//com.oracle.svm.core.code.RuntimeCodeInfo.logMethod(RuntimeCodeInfo.java:338)
    jdk.internal.ref.CleanerImpl$PhantomCleanableRef.get()]
com.oracle.svm.core.util.UserError$UserException: @RestrictHeapAccess warning: Restricted method: 'ThreadLocalAllocation.slowPathNewArrayWithoutAllocating(Class, int)' calls 'CleanerImpl$PhantomCleanableRef.get()' that violates restriction NO_ALLOCATION.
  [Path:
    app//com.oracle.svm.core.genscavenge.ThreadLocalAllocation.slowPathNewArrayWithoutAllocating(ThreadLocalAllocation.java:224)
    app//com.oracle.svm.core.genscavenge.ThreadLocalAllocation.allocateNewArray(ThreadLocalAllocation.java:233)
    app//com.oracle.svm.core.genscavenge.HeapImpl.exitIfAllocationDisallowed(HeapImpl.java:293)
    app//com.oracle.svm.core.heap.NoAllocationVerifier.exit(NoAllocationVerifier.java:61)
    app//com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.shouldNotReachHere(VMErrorSubstitutions.java:59)
    app//com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.shouldNotReachHere(VMErrorSubstitutions.java:74)
    app//com.oracle.svm.core.jdk.VMErrorSubstitutions.shutdown(VMErrorSubstitutions.java:112)
    app//com.oracle.svm.core.jdk.VMErrorSubstitutions.doShutdown(VMErrorSubstitutions.java:150)
    app//com.oracle.svm.core.SubstrateUtil.printDiagnostics(SubstrateUtil.java:270)
    app//com.oracle.svm.core.SubstrateUtil.dumpRuntimeCompilation(SubstrateUtil.java:424)
    app//com.oracle.svm.core.SubstrateUtil.dumpRuntimeCodeCacheTable(SubstrateUtil.java:445)
    app//com.oracle.svm.core.code.RuntimeCodeInfo.logTable(RuntimeCodeInfo.java:329)
    app//com.oracle.svm.core.code.RuntimeCodeInfo.logMethod(RuntimeCodeInfo.java:338)
    jdk.internal.ref.CleanerImpl$PhantomCleanableRef.get()]
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.code.RestrictHeapAccessAnnotationChecker$RestrictHeapAccessWarningVisitor.postRestrictHeapAccessWarning(RestrictHeapAccessAnnotationChecker.java:201)
	at com.oracle.svm.hosted.code.RestrictHeapAccessAnnotationChecker$RestrictHeapAccessWarningVisitor.visitMethod(RestrictHeapAccessAnnotationChecker.java:144)
	at com.oracle.svm.hosted.code.RestrictHeapAccessAnnotationChecker.check(RestrictHeapAccessAnnotationChecker.java:77)
	at com.oracle.svm.hosted.code.CompileQueue.finish(CompileQueue.java:350)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:599)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:442)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
```

**Comment by bobmcwhirter** [comment]
So it actually appears that the `exitIfAllocation` isn't the real cause, but the error logging after that exit, maybe, during shutdown? Some flag not being cleared once the `shouldNotReachHere` has thrown?

**Comment by dougxc** [comment]
Looks like points-to analysis gone wrong as `Reference.get()` does not appear to be called from `ThreadLocalAllocation.slowPathNewArrayWithoutAllocating(...)`. @cstancu or @christianwimmer  may have more insights.

**Comment by bobmcwhirter** [comment]
It seems that when something fails/exits, we ultimately hit `printDiagnostics` which does indeed ultimately reach `Reference.get()` in `RuntimeCodeInfo.logMethod(...)`

https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/code/RuntimeCodeInfo.java#L338

**Comment by bobmcwhirter** [comment]
It I make `printDiagnostics` an empty no-op method, then the build proceeds.

**Comment by bobmcwhirter** [comment]
Added another commit which no-ops printDiagnostics, continues to change mx scripts, and safely guards around an empty string for `com.oracle.graalvm.launcher.launcherclasses` property (which may be the wrong solution to the wrong problem).

You can now build without disabling polyglot/libpolyglot:

    mx clean &&  mx -V  --dynamicimports /substratevm

**Comment by christianwimmer** [comment]
Looks like in JDK 11 there is a new override of `Reference.get`, `CleanerImpl$PhantomCleanableRef.get()`, that might allocate. It is generally not a good idea to access the a `WeakReference` during diagnostic printing, so I'm going to remove that part of the diagnostic printing code.

**Comment by bobmcwhirter** [comment]
When building for aarch64, the `native-image` native image seems to failing in `Unsafe.copyMemory0(...)` because it's taking a C pointer to the environment, and adding it to the base heap instead of leaving it unmolested as a bonafide valid point to un-managed memory.

Not sure where to go from here, but I'll keep poking, but if anyone has any wisdom, I'm all ears.

**Comment by bobmcwhirter** [comment]
@sanzinger -- Question: 

Where is it decided that heapBase is added to an address? As noted above, the problem is a `CCharPointer` which is a valid opaque pointer (to the env-vars string) is being adjusted by heap-base into a segfault, instead of being left unmolested.

Happens within the first 3 asm instructions in a method, against the method parameter registers.

Also, when native-imaging native-image itself, `-H:Dump=` and/or `-Dgraal.Dump=` isn't producing any bgv/cfg files, so I'm unable to use IGV to poke around the structure of wtf is happening.

Thanks.

**Comment by adinn** [comment]
Hi Bob,

I think this is hapepnign because of lack of support for JDK11 translation in SubstarteVM.

When targetting Hotspot the translation of Unsafe calls is done using a Graal compiler plugin. In Hotspot the translation of copyMemory calls is done by class HotSpotUnsafeSubstitutions which is installed by method registerUnsafePlugins of class HotSpotGraphBuilderPlugins. This is configured when the compiler suite is created.

The Substrate JDK8 code provides a substitution for the version wihc takes object arguments in class SunMiscSubstitutions. It doesn't provide a variant for the version that takes long args. In JDK11 the plugin replaces calls to underlying method copymemory0. Only that doesn't have a seem to have SubstrateVM substitution.

**Comment by bobmcwhirter** [comment]
@adinn THANK YOU!

I saw the unsafe plugins, and the switches related to `Java11OrEarlier`, but had missed the package name differences.

Thanks!

**Comment by bobmcwhirter** [comment]
Actually...

```
#0  0x0000000000405318 in MemoryUtil_copyConjointBytesAtomic_388d1871b3c077966c1f94f0a88df10b46a2c88b ()
#1  0x00000000004054f8 in MemoryUtil_copyConjointMemoryAtomic_174b0d7e8b7732fb943128a077ca719669b292d3 ()
#2  0x00000000008d0388 in Unsafe_copyMemory0_132762b08ba3ece6d969b78015819f0564a58803 ()
#3  0x00000000008d0300 in Unsafe_copyMemory_38b26f405246e2c79cba9e0e9badaff69b863bb5 ()
#4  0x0000000000623314 in DirectByteBuffer_get_d4edfcd04ddabed9f1100e4c6988557e0f7602ec ()
```

The substitution for `JDK9OrLater` seems to be wired up and poking through `MemoryUtils`, I think. But it's still doing heap-base math on the argument. Maybe because of the jump through the non-substituted `copyMemory()` prior to hitting the substituted `copyMemory0()`.

I'll keep poking, but definitely thanks for the pointer to the right direction.

**Comment by adinn** [comment]
On 17/04/2019 16:54, Bob McWhirter wrote:
> Actually...
> 
> |#0 0x0000000000405318 in
> MemoryUtil_copyConjointBytesAtomic_388d1871b3c077966c1f94f0a88df10b46a2c88b
> () #1 0x00000000004054f8 in
> MemoryUtil_copyConjointMemoryAtomic_174b0d7e8b7732fb943128a077ca719669b292d3
> () #2 0x00000000008d0388 in
> Unsafe_copyMemory0_132762b08ba3ece6d969b78015819f0564a58803 () #3
> 0x00000000008d0300 in
> Unsafe_copyMemory_38b26f405246e2c79cba9e0e9badaff69b863bb5 () #4
> 0x0000000000623314 in
> DirectByteBuffer_get_d4edfcd04ddabed9f1100e4c6988557e0f7602ec () |
> 
> The substitution for |JDK9OrLater| seems to be wired up and poking
> through |MemoryUtils|, I think. But it's still doing heap-base math on
> the argument. Maybe because of the jump through the non-substituted
> |copyMemory()| prior to hitting the substituted |copyMemory0()|.
Hmm. The 3 arg version passes null for theobjects to the 5 arg version.
Is it getting maybe confused between null == 0 and null == heapbase?

regards,


Andrew Dinn
-----------
Senior Principal Software Engineer
Red Hat UK Ltd
Registered in England and Wales under Company Registration No. 03798903
Directors: Michael Cunningham, Michael ("Mike") O'Neill, Eric Shander

**Comment by bobmcwhirter** [comment]
@adinn -- you nailed it. AArch64 backend was missing the code for converting to/from null and zero.

I have other problems now, but yay!

**Comment by bobmcwhirter** [comment]
@adinn -- fix here: https://github.com/oracle/graal/pull/1176

**Comment by adinn** [comment]
Nice on Bob!

**Comment by bobmcwhirter** [comment]
Replaced with https://github.com/oracle/graal/pull/1245

**Pull request closed without merging**
