### PR TITLE
Detect usage of resources loaded through `jdk.internal.jimage.BasicImageReader`

### PR DESCRIPTION
**Pull request by koutheir**
Add support, in `native-image-agent`, for detection of resources loaded through `jdk.internal.jimage.BasicImageReader` and classes derived from it.

### CODE REVIEW

**Comment by koutheir** [comment]
The failure in checks do not seem related to this change.

**Comment by peter-hofer** [comment]
How does application code use these methods? The problem with instrumenting methods within the JDK is that we can't distinguish JDK-internal usage from usage in user code and cannot accurately filter, so it is preferable to instrument those methods that are called from application code directly.

**Comment by koutheir** [comment]
I think it was `Module.getResourceAsStream()` and methods like it.

**Review by peter-hofer — CHANGES_REQUESTED** [review]
Thank you, please change the PR accordingly.

**Comment by koutheir** [comment]
Too many methods seem to be calling `BasicImageReader.findLocation(String)` and `BasicImageReader.findLocation(String,String)`. I don't think I can find all of them without extensive testing and tracing.

**Pull request closed without merging**
