### PR TITLE
Build SVM with JDK 19.

### PR DESCRIPTION
**Pull request by oraluben**
Ref: graalvm/mx#263

### CODE REVIEW

**Comment by oraluben** [comment]
Hi @christianhaeubl, do you have any clue why some JDK 11 gates failed? I think I didn't change JFR things, but only some substitutions.

One failure in gate:
```
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: jdk.jfr.internal.EventWriter.reset(). This error is reported at image build time because class jdk.jfr.internal.handlers.EventHandler25496_1656418948447-15258 is registered for linking at image build time by command line
	at parsing jdk.jfr.internal.handlers.EventHandler25496_1656418948447-15258.write(Unknown Source)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2506)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:105)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3367)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3319)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3164)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:79)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:261)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:684)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:168)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:343)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
```

All two failed gates:
https://github.com/oracle/graal/runs/7092214399?check_suite_focus=true
https://github.com/oracle/graal/runs/7092215106?check_suite_focus=true

**Comment by christianhaeubl** [comment]
@oraluben I don't see anything that is obviously wrong. Most likely, it has something to do with your `jdk.jfr.internal.handlers.EventHandler` substitution class. You could try to debug the image build but @zapster is also currently working on the update to JDK 19. He uses different solution for fixing the JFR differences between the JDK versions.

**Comment by zapster** [comment]
hi @oraluben! See here the first of many JDK 19 PRs (#4692). It only fixes compiling and only for the /substratevm suite. There is also work in progress on the /compiler suite, but that will be delivered in a different PR.

**Comment by oraluben** [comment]
@zapster Thanks for sharing! Looking forward to future updates

**Pull request closed without merging**
