### PR TITLE
[Backport][22.3] Only require libmanagement_ext if it's actually needed.

### LINKED ISSUE #5273: [22.3]: Backport Request: libmanagement_ext.a unconditionally being added when libawt_headless.a is linked in
The fix of https://github.com/oracle/graal/issues/5119 didn't end up in the 22.3 release tree. We'd like to backport this fix to 22.3.1 if possible.

The change applies cleanly to the 22.3 tree, we've backported it to our mandrel/22.3 branch already. I'd be happy to create a PR targetting the release branch for this.

/cc @gilles-duboscq @ezzarghili as per https://github.com/oracle/graal/discussions/4332#discussioncomment-2361015

### PR DESCRIPTION
**Pull request by zakkak**
Backports #5122 (backport applied cleanly)
Closes #5273

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
LGTM

**Comment by oubidar-Abderrahim** [comment]
@ezzarghili could you please review this PR, please let me know when the PR is ready to be mirrored to bitbucket. Thank you

**Comment by ezzarghili** [comment]
LGTM, @oubidar-Abderrahim please follow up on this PR.
Proceed with internal integration.

**Comment by jerboaa** [comment]
Any update on this?

**Comment by ezzarghili** [comment]
The PRs are merged into our CPU branched internally, they will show up once they get mirrored to GitHub.

**Pull request merged**
