### PR TITLE
fixe OS languages - Arch and Version detection

### PR DESCRIPTION
**Pull request by Ferhatos**
Fixe to support for any OS language

### CODE REVIEW

**Comment by olpaw** [comment]
@Ferhatos I don't see why wee need this. See https://github.com/oracle/graal/pull/2499#issuecomment-635246987

**Comment by Ferhatos** [comment]
Hello @olpaw ,

I've seen that issue still there for German OS as commented, and that there is some specific code for a specific OS language. This PR is to be more generic without specific code, for any OS language environment.

Still don't agree ?

**Comment by olpaw** [comment]
> I've seen that issue still there for German OS as commented, and that there is some specific code for a specific OS language. This PR is to be more generic without specific code, for any OS language environment.
> 
> Still don't agree ?

Thanks for your PR but so far, I do not see any reason for merging this PR.

I have - of course - also tested my current approach (what we now have on master) with
```
Microsoft (R) C/C++-Optimierungscompiler Version 19.26.28805 für x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Syntax: cl [ Option... ] Dateiname... [ /link Linkeroption... ]
```
and it works fine, just like with the French, Simplified-Chinese and all other variants people posted on https://github.com/oracle/graal/issues/2480.

Your PR searches for the architecture string in an unstructured way (`Matcher archMatcher = Pattern.compile("x[0-9]+[0-9]+").matcher(versionMessage);`) which is suboptimal because it only works for the architectures that you have hard-coded so far. What about ARM or ARM64? Are we going to change the pattern every time we support a new architecture?
Also I don't see why the if-cascade for version number parts is better than using scanner with `hasNextInt/nextInt` + custom delimiter.

As I already said before, if it turns out the current approach is insufficient we will instead implement the approach mentioned here: https://github.com/oracle/graal/issues/2480#issuecomment-633469170

**Comment by Ferhatos** [comment]
Hello @olpaw ,
Thank you for your detailed response. I missed other architectures and you're right.
I've seen later **if-cascades**, it can be optimized using _matcher group function_ (`matcher.group(index)`) by adding `()` in **RegExp**.

Thank you.
Any idea when can we use the fixe for languages ?

**Pull request closed without merging**
