### PR TITLE
Compute parameters for Executable objects

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
I am already covered by the OCA.

**Comment by dmlloyd** [comment]
Fixes #539

**Comment by cstancu** [comment]
Thanks for your contribution. I'll take a close look early next week. There is an alternative solution that may be simpler.

**Comment by panga** [comment]
I hit in the same error. Merging the @dmlloyd fix worked for me.

**Comment by cstancu** [comment]
Yes, the changes are valid and fix the problem. I'll bring them in as part of a bigger refactoring of the reflection meta-data caching.

**Comment by cstancu** [comment]
Thanks for your contribution. The PR has been merged. As I was hinting at above I additionally refactored the reflection metadata computation. We don't need a custom field recomputation for lazily computed field values. It is enough to invoke the method that leads to the field initialization in an object replacer, i.e., at image build time, to add that value to the native image heap. See [here](https://github.com/oracle/graal/commit/76595b624175650d143e7775dce1a1ae9d060368#diff-8d00382cbe8559ce3a72dc0b4c36f093R48).

**Pull request merged**
