### PR TITLE
[Backport][22.3] Fallback from PosixPerfMemoryProvider to CHeapPerfMemoryProvider.

### PR DESCRIPTION
**Pull request by galderz**
Backport fix for https://github.com/oracle/graal/issues/5303 for 22.3 branch.

### CODE REVIEW

**Review by zakkak — APPROVED** [review]
LGTM.

This is a clean backport of https://github.com/oracle/graal/commit/62432ef3b318bf4eae3c50d3e612cca8208bd988

**Comment by ezzarghili** [comment]
@oubidar-Abderrahim Please coordinate with @marwan-hallaoui on internal integration for this PR.

**Comment by ezzarghili** [comment]
LGTM

**Review by ezzarghili — CHANGES_REQUESTED** [review]
When cherry-picking commits, please use the -X flag to retain the original commit reference.

**Comment by galderz** [comment]
@ezzarghili You mean `-x` rather than `-X`? I've just pushed again having passed `-x`.

**Comment by jerboaa** [comment]
Any update on this? Can we assume this makes it into 22.3.1?

**Comment by ezzarghili** [comment]
The PR is merged into our CPU branched internally, they will show up once they get mirrored to GitHub.

**Comment by jerboaa** [comment]
Thanks!

**Comment by oubidar-Abderrahim** [comment]
>  You mean -x rather than -X? I've just pushed again having passed -x.

Sorry @galderz, I started the integration process before this change and missed it. The backport was integrated in the 22.3 branch here: https://github.com/oracle/graal/commit/45bf93a31261d3ba0db38304845ea4325c7ed3f1

**Pull request closed without merging**
