### PR TITLE
[GR-16855] Remove builder classpath entries from imagecp.

### PR DESCRIPTION
**Pull request by olpaw**

### CODE REVIEW

**Comment by olpaw** [comment]
TODO: Add a fix to ensure `truffle-api.jar` is only on the module-path if needed (building of truffle images).

**Comment by olpaw** [comment]
@adinn as part of this PR I also refactored the SourceCache  class hierarchy. See: 32db602b60a731f33b65f5f22711338c1ef4883d
Pleas have a quick look if my changes look ok for you. Thx!

**Comment by olpaw** [comment]
> TODO: Add a fix to ensure `truffle-api.jar` is only on the module-path if needed (building of truffle images). See [#2129 (comment)](https://github.com/oracle/graal/issues/2129#issuecomment-621643022)

https://github.com/oracle/graal/pull/2415/commits/691923f6188ce0c5d6a9233024e4208fe7d8fbab

**Comment by adinn** [comment]
@olpaw The source cache changes look ok. I probably should have done it that way in the first place!

**Pull request closed without merging**
