### PR TITLE
Fix a typo [ci skip]

### PR DESCRIPTION
**Pull request by fniephaus**

### CODE REVIEW

**Comment by fniephaus** [comment]
Did you just got yourself in trouble with the oca-check bot, @Best Regards

**Comment by fniephaus** [comment]
Did you just get yourself in trouble with the oca-check bot, @boris-spas? 😅

(closed PR by mistake, yes...I'm fighting with the tools too)

**Comment by boris-spas** [comment]
> Did you just get yourself in trouble with the oca-check bot, @boris-spas? 
Looks like it :D The bot is not too bright, but we like it anyway :)

**Comment by boris-spas** [comment]
Merged in 19ea1c73f07d2ed73b51bb66414501c07d12d4c0

**Pull request closed without merging**
