### PR TITLE
[GR-48354] Consolidate application module name detection.

### PR DESCRIPTION
**Pull request by graalvmbot**
This PR re-implements the module name detection needed in the driver to not require running a jvm command anymore.

In addition to that there are some smaller cleanups.

### CODE REVIEW

**Comment by jerboaa** [comment]
@olpaw Thanks for the heads-up. This still fails the build with `--no-jlinking` option. Do you want to fix this as part of this PR or shall I with a rebased version of #7205?

**Comment by olpaw** [comment]
@jerboaa this is now in good shape and will be merged soon. Once on master please create a PR with any remaining changes needed for mandrel.

**Comment by jerboaa** [comment]
> @jerboaa this is now in good shape and will be merged soon. Once on master please create a PR with any remaining changes needed for mandrel.

@olpaw Excellent! Sure I have a PR handy locally. I'll be rebasing #7205 as far as the patch is concerned. Hope that's OK too?

**Comment by olpaw** [comment]
> @olpaw Excellent! Sure I have a PR handy locally. I'll be rebasing #7205 as far as the patch is concerned. Hope that's OK too?

Yes, except for the changes in `buildImage()`. These you do not need anymore.

**Comment by jerboaa** [comment]
> > @olpaw Excellent! Sure I have a PR handy locally. I'll be rebasing #7205 as far as the patch is concerned. Hope that's OK too?
> 
> Yes, except for the changes in `buildImage()`. These you do not need anymore.

Sure, understood. Thanks!

**Review by jerboaa — APPROVED** [review]

**Comment by jerboaa** [comment]
> @jerboaa do you approve this PR?

Sure. Sorry if this was waiting on myself (if so, I wasn't aware).

**Comment by jerboaa** [comment]
@fniephaus @olpaw Any ETA when this will merge?

**Comment by fniephaus** [comment]
It's on the top of the merge queue, should be merged in the next couple of minutes.

**Comment by jerboaa** [comment]
Great, thanks!

**Comment by jerboaa** [comment]
OK. Thanks for the update.

**Comment by olpaw** [comment]
@jerboaa this is now on master. Feel free to create your PR now that fixes the remaining issues that needed for mandrel.

**Comment by jerboaa** [comment]
> @jerboaa this is now on master. Feel free to create your PR now that fixes the remaining issues that are needed for mandrel.

@olpaw Yes, thanks! Already done in #7205. Please review once you get a chance.

**Pull request closed without merging**
