### PR TITLE
temp fix for #975 create a single module

### PR DESCRIPTION
**Pull request by johanvos**
Class.getModule() now works, but --report-unsupported-elements-at-runtime needs to be added when building image

### CODE REVIEW

**Comment by johanvos** [comment]
https://www.oracle.com/technetwork/community/oca-486395.html contains my name

**Comment by olpaw** [comment]
@johanvos thanks for the contribution. Unfortunately in the current form we cannot merge the patch as it will force users to users to use `--report-unsupported-elements-at-runtime` where they previously did not need it. E.g. Building a simple image that uses ProcessBuilder.start() will make the analysis see
```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method java.lang.ClassLoader.packages() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing java.base@11/java.lang.Module.getPackages(Module.java:1050)
Call path from entry point to java.lang.Module.getPackages(): 
	at java.base@11/java.lang.Module.getPackages(Module.java:1042)
	at java.base@11/java.lang.Module.getResourceAsStream(Module.java:1553)
	at java.base@11/sun.util.resources.BreakIteratorResourceBundle.lambda$getResourceAsStream$0(BreakIteratorResourceBundle.java:85)
	at java.base@11/sun.util.resources.BreakIteratorResourceBundle$$Lambda$413/0x0000000800df7440.run(Unknown Source)
	at app//com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:83)
	at java.base@11/java.lang.ProcessImpl.<init>(ProcessImpl.java:351)
	at java.base@11/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base@11/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	at java.base@11/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
```
I suggest to also provide a substitution for `java.lang.Module.getResourceAsStream` (possibly implemented via `com.oracle.svm.core.jdk.Target_java_lang_ClassLoader#getSystemResourceAsStream`).

**Comment by johanvos** [comment]
I agree with that (hence the WIP in the name of the PR ;) )

**Comment by johanvos** [comment]
--report-unsupported-elements-at-runtime is not longer needed (because of the substitution of Module.getResourceAsStream)

**Comment by olpaw** [comment]
This is ok now. Please rebase your commits so that
* `remove debug info` folded into `Add substitution for Module.getResourceAsStream()`
* `create a single module and always ret...` starts with `Create ....`
then I can merge your changes.

**Comment by johanvos** [comment]
That should be done now.

**Pull request merged**
