### PR TITLE
Improve AbsNode canonicalization

### PR DESCRIPTION
**Pull request by kethomassen**
- Adds an extra canonicalization to AbsNode with NegateNode inputs.
- Fixed an incorrect return value in create factory method.

### CODE REVIEW

**Comment by kethomassen** [comment]
@graalvmbot I have signed the OCA.

**Comment by gergo-** [comment]
Thanks for adding these tests! Please fix the formatting issue found by https://github.com/oracle/graal/pull/3364/checks?check_run_id=2564900947. You should be able to run `mx checkstyle` locally to make sure that your formatting is OK.

**Comment by kethomassen** [comment]
Seems to be because the new file is missing the Oracle license header. Not sure what the process with this is: copy paste it from another file and change the copyright year to 2021, or leave the copyright year unchanged?

**Comment by gergo-** [comment]
> Seems to be because the new file is missing the Oracle license header. Not sure what the process with this is: copy paste it from another file and change the copyright year to 2021, or leave the copyright year unchanged?

2021 is good. Note though that it's not just the license header, the formatting of the code is really off. Maybe you need eclipseformat installed for that part of the check to be run; maybe `mx eclipseformat` will do it for you.

**Comment by kethomassen** [comment]
Ah yes, I didn't have eclipse installed so those errors didn't show up in `mx checkstyle` for me - fixed now. However, it appears now the CI build is failing due to Sulong code this PR hasn't touched?

**Comment by gergo-** [comment]
> However, it appears now the CI build is failing due to Sulong code this PR hasn't touched?

I think the `mx` version of that gate might be slightly out of sync with your branch of GraalVM, since you branched off several weeks ago. The same test passed in our internal CI. I'll try to get this branch merged soon. Thank you again for this contribution!

**Pull request merged**
