### PR TITLE
Fix search for "nearby" bin/java(.exe).

### PR DESCRIPTION
**Pull request by bobmcwhirter**
By default, native-image would jump too high up before
looking for a nearby bin/java(.exe) prior to just looking
around in $JAVA_HOME.

Still, searches the same paths, but slowly jumps up from
the `rootDir` instead of immediately searching `rootDir.getParent()`.

Additionally, refactored to avoid duplicate logic.

### CODE REVIEW

**Comment by olpaw** [comment]
Once the trivial/style related issued are fixed (i.e. the travis gates pass) I will pick it up.

**Comment by bobmcwhirter** [comment]
Right on, will fix and push again in a few.

Thanks!

**Comment by bobmcwhirter** [comment]
Done

**Comment by olpaw** [comment]
@bobmcwhirter I think latest master changes on master make this PR obsolete. Do you agree?

**Comment by bobmcwhirter** [comment]
Seems Giles is fixing it in parallel yeah. 

Would be easier to track if all contributors (including ORCL) used the same PR process.

**Comment by bobmcwhirter** [comment]
Actually Giles is doing AdoptOpenJDK (another PR of mine). I’ll have to check master commits wrt nearby bin/java once I’m not on my phone.

**Comment by olpaw** [comment]
> Would be easier to track if all contributors (including ORCL) used the same PR process.

I agree.

**Comment by bobmcwhirter** [comment]
Yah, seems fixed by

https://github.com/oracle/graal/commit/404359e56616d386531933d6a8d65fc95cbcbc17

**Pull request closed without merging**
