### PR TITLE
Support byte arrays on platforms without unaligned access, depending on platform endiannes

### PR DESCRIPTION
**Pull request by koutheir**
Support byte arrays on platforms without unaligned access, depending on platform endiannes.

### CODE REVIEW

**Comment by koutheir** [comment]
@graalvmbot, I already signed the OCA on 2018-04-03.

**Comment by koutheir** [comment]
The failed checks do not seem to be related to this patch.

**Comment by gilles-duboscq** [comment]
Regarding the gate checks, they were fixed by #3478, i guess your PR stems from before that.

**Comment by koutheir** [comment]
I rebased on top of the last HEAD, and the failed checks do not seem to be related to this patch.

**Comment by gilles-duboscq** [comment]
Thanks. I think after those 2 tests got fixed, all the tests got broken for some other reason :frowning_face:

**Comment by gilles-duboscq** [comment]
Could you describe a bit more the issue you are fixing here?
As far as I can tell, `SimpleByteArraySupport` always in a big-endian fashion so i'm not sure it's OK to use it for `LITTLE_ENDIAN`.

**Comment by koutheir** [comment]
> As far as I can tell, `SimpleByteArraySupport` always in a big-endian fashion so i'm not sure it's OK to use it for `LITTLE_ENDIAN`.

I missed that. This makes this PR invalid. I'm closing it.

**Pull request closed without merging**
