### PR TITLE
Remove substitutions for DatagramDispatcher

### LINKED ISSUE #1787: native-image: DatagramDispatcher not implemented
Attempting to read/write on a DatagramChannel from an application built with native-image results in:
```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Unimplemented: sun.nio.ch.DatagramChannelImpl.receive0(FileDescriptor, long, int)
    at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
    at sun.nio.ch.DatagramDispatcher.write0(DatagramDispatcher.java:108)
    at sun.nio.ch.DatagramDispatcher.write(DatagramDispatcher.java:51)
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
    at sun.nio.ch.IOUtil.write(IOUtil.java:65)
```

This is caused by DatagramDispatcher substitutions throwing an exception (don't be misled by the wrong error message).

### PR DESCRIPTION
**Pull request by mziccard**
Fixes #1787

### CODE REVIEW

**Comment by christianwimmer** [comment]
We have already switched the default to link in C code of the JDK instead of using the (now deprecated) substitution mechanism. 
So I don't see how this PR can fix the test cases also included in this PR - it only changes unused code.

**Comment by christianwimmer** [comment]
You are correct, there are a couple of `unimplemented` substitutions that need to go away. I'll probably make my own PR for that because getting your signed OCA signed and registered will probably take a while, and that is something we need to fix in our upcoming 19.3 release.

**Comment by mziccard** [comment]
@christianwimmer I did actually sign the OCA but apparently it's taking some time to be processed. I'll leave this with you, feel free to close or merge, either way I won't take it personally :)

**Comment by christianwimmer** [comment]
The fix to disable the `Target_sun_nio_ch_DatagramDispatcher` substitution (and others too) is merged. So the only thing left from this PR that could be merged is the test.

**Comment by mziccard** [comment]
Closing this as it was fixed in b4b654a793f45588928618c8174817145277eeed

**Pull request closed without merging**
