### PR TITLE
[GR-34478] Add missing module info for SVM MBeans.

### LINKED ISSUE #3875: java.lang.NoClassDefFoundError: sun.management.Util in runtime on JDK 17
**Describe the issue**
`ManagementFactory.getPlatformMBeanServer` in native-image (JDK 17) throws NoClassDefFoundError.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1.
```
public class Test {
    public static void main(String[] args) {
        System.out.println(java.lang.management.ManagementFactory.getPlatformMBeanServer());
    }
}
```
2. `javac Test.java`
3. `native-image --no-fallback --allow-incomplete-classpath Test`
4. `./test`
5. NoClassDefFoundError

**Describe GraalVM and your environment:**
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment GraalVM CE 21.3.0-dev (build 17+35-jvmci-21.3-b03)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0-dev (build 17+35-jvmci-21.3-b03, mixed mode, sharing)
```
 - JDK major version: **17**
 - OS: **Linux**
 - Architecture: **AMD64**

**More details**
```
Exception in thread "main" java.lang.NoClassDefFoundError: sun.management.Util
	at com.oracle.svm.core.jdk.management.SubstrateCompilationMXBean.getObjectName(SubstrateCompilationMXBean.java:47)
	at com.oracle.svm.core.jdk.management.ManagementSupport.addMXBean(ManagementSupport.java:267)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:259)
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:45)
	at Test.main(Test.java:4)
```

### PR DESCRIPTION
**Pull request by graalvmbot**
Fixes #3875

### CODE REVIEW

**Comment by zakkak** [comment]
Hi @pejovica, is this going to get backported to 20.3 as well for the January release?

**Comment by jerboaa** [comment]
> Hi @pejovica, is this going to get backported to 20.3 as well for the January release?

@zakkak `21.3` I take it?

**Comment by zakkak** [comment]
:facepalm: Right Severin, thanks!

**Comment by pejovica** [comment]
@zakkak Yes, it will be backported to `21.3`.

**Pull request merged**
