### PR TITLE
Prevent exception from being swallowed in maven-plugin

### PR DESCRIPTION
**Pull request by bdemers**
Adds root cause to MojoExecutionException when an IllegalAccessError is thrown

### CODE REVIEW

**Comment by bdemers** [comment]
I'm trying to track down an error on windows, when the native-image-maven-plugin is used, but the root cause is ignored

**Comment by olpaw** [comment]
@bdemers your change looks fine. Please sign the OCA so that I can merge your change. Thanks.

**Comment by bdemers** [comment]
@olpaw, I sent it in last night, let me known if it doesn’t show up in the system!

**Comment by olpaw** [comment]
> @olpaw, I sent it in last night, let me known if it doesn’t show up in the system!

@dougxc how long does it usually take nowadays to get graalvmbot to see submitted OCAs? Is that process still manual?

**Comment by dougxc** [comment]
Yep, still manual. First we need to see the OCA show up [here](http://www.oracle.com/technetwork/community/oca-486395.html). Then we need to edit the OCA database used by @graalvmbot .

**Comment by bdemers** [comment]
@olpaw @dougxc I'm listed on the OCA page now 😄

**Pull request merged**
