### PR TITLE
Add RSS reporting for Linux

### LINKED ISSUE #3879: native image build should report RSS size of build process
**Feature request**

Add resident set size memory information to the native image build process for a more accurate picture of consumed memory.

**Is your feature request related to a problem? Please describe.**
We frequently analyze the native image build process for memory consumption. While it shows the [current heap capacity]( https://github.com/oracle/graal/blob/d03e3b3a5192b8e6ef205d507bf9b46de48c8459/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/util/Timer.java#L90) (via `Runtime.getRuntime().totalMemory()`), but that's not the total picture as it only showing (some) heap information. There are other things consuming memory. Native GC structures, Class metadata, JIT compiler code caches, etc. This is particularly relevant on cloud systems where the build process might run with a memory limit and the native-image build process gets seemingly killed too early by the Linux OOM killer. The memory reporting of the native-image build process seemingly shows that there is still some room left. That can leave users confused.

**Describe the solution you'd like.**
Include resident set size (RSS) of the processes' virtual memory in addition to heap consumption for the native image build process. Example:

```
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]    classlist:  15,819.63 ms,  1.19 GB 0.71 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]        (cap):     691.90 ms,  1.19 GB 0.73 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]        setup:   2,464.19 ms,  1.19 GB 0.74 GB (VmRSS)
The bundle named: messages, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.
17:07:37,727 INFO  [org.hib.Version] HHH000412: Hibernate ORM core version 5.5.7.Final
17:07:37,812 INFO  [org.hib.ann.com.Version] HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
17:07:38,044 INFO  [org.hib.dia.Dialect] HHH000400: Using dialect: io.quarkus.hibernate.orm.runtime.dialect.QuarkusPostgreSQL10Dialect
17:09:02,211 INFO  [org.jbo.threads] JBoss Threads version 3.4.2.Final
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]     (clinit):   1,169.83 ms,  3.02 GB 3.49 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]   (typeflow): 118,958.38 ms,  3.02 GB 3.49 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]    (objects):  91,161.64 ms,  3.02 GB 3.49 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]   (features):   1,574.82 ms,  3.02 GB 3.49 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]     analysis: 215,031.84 ms,  3.02 GB 3.49 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]     universe:   7,198.35 ms,  3.02 GB 3.53 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]      (parse):  23,000.72 ms,  2.84 GB 3.76 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]     (inline):  21,371.34 ms,  2.83 GB 3.70 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]    (compile): 214,593.69 ms,  3.04 GB 3.74 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]      compile: 261,936.51 ms,  3.04 GB 3.74 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]        image:   9,250.12 ms,  2.98 GB 3.78 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]        write:   1,459.14 ms,  2.98 GB 3.77 GB (VmRSS)
[spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner:47]      [total]: 513,565.72 ms,  2.98 GB 3.77 GB (VmRSS)
# Printing build artifacts to: /project/spring-to-quarkus-todo-0.0.1-SNAPSHOT-runner.build_artifacts.txt
```

**Describe who do you think will benefit the most.**
GraalVM users, GraalVM contributors, developers of libraries and frameworks which depend on GraalVM.

**Describe alternatives you've considered.**
I've done some experiments to hook this onto the existing native-image output. For Linux this can be done via:
```
native-image <native-image-args> | while read line; do echo -n "$line"; pid=$(echo "$line" | grep '^\[' | awk '{ print $1 }' | sed 's/\[//g' | sed 's/\]//g' | cut -d':' -f2); if [ "${pid}_" != "_" ]; then grep VmRSS /proc/$pid/status | awk '{ print $2 }' | awk '{ val=$1 / 1024; val=val/1024; printf "%5.2f GB (VmRSS)\n", val }'; else echo; fi; done
```
but this isn't easy to put into all possible build pipelines. A GraalVM patch seems the better approach.

**Express whether you'd like to help contributing this feature**
Feel free to assign this feature request to myself. I'll get an initial version (for Linux) implemented. If relevant parties can show me the corresponding Windows/Mac APIs I'd be happy to incorporate.

### PR DESCRIPTION
**Pull request by jerboaa**
As an observation the "memory usage" printed before this patch
was the heap capacity retrieved via API
`Runtime.getRuntime().totalMemory()`. The actual intent seemed to
be to print the heap usage, retrievable with API:
`Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory()`
    
This patch changes the output to dispaly heap usage instead.
Additionally, the resident set size (rss) is being displayed for
Linux. Implementations of other platforms may follow.
    
Closes #3879

### CODE REVIEW

**Comment by jerboaa** [comment]
Output on Windows looks like this:

```
[hello:2844]    classlist:   4,162.74 ms,  0.26 GB (heap)
[hello:2844]        (cap):   1,671.73 ms,  0.34 GB (heap)
[hello:2844]        setup:   3,724.73 ms,  0.38 GB (heap)
[hello:2844]     (clinit):     249.97 ms,  0.52 GB (heap)
[hello:2844]   (typeflow):   3,353.86 ms,  0.52 GB (heap)
[hello:2844]    (objects):   4,156.31 ms,  0.52 GB (heap)
[hello:2844]   (features):   3,336.44 ms,  0.52 GB (heap)
[hello:2844]     analysis:  11,532.53 ms,  0.52 GB (heap)
[hello:2844]     universe:     811.44 ms,  0.73 GB (heap)
[hello:2844]      (parse):     981.25 ms,  0.94 GB (heap)
[hello:2844]     (inline):     636.26 ms,  1.63 GB (heap)
[hello:2844]    (compile):   6,968.53 ms,  2.36 GB (heap)
[hello:2844]      compile:   9,225.96 ms,  2.42 GB (heap)
[hello:2844]        image:   1,302.12 ms,  2.61 GB (heap)
[hello:2844]        write:     407.68 ms,  2.63 GB (heap)
[hello:2844]      [total]:  31,506.46 ms,  2.63 GB (heap)
```

I'm not sure if it's desired to implement this on windows as it would require some JNI code.

**Comment by jerboaa** [comment]
Check failures seem to be infra related.

**Comment by fniephaus** [comment]
As part of #3955, I have implemented RSS reporting based on JNI so that it works across Linux, macOS, and Windows. So maybe we no longer need this PR and can close it once the new output has landed in NI?

**Comment by jerboaa** [comment]
> As part of #3955, I have implemented RSS reporting based on JNI so that it works across Linux, macOS, and Windows. So maybe we no longer need this PR and can close it once the new output has landed in NI?

Sure. Happy to close this one once PR for #3955 lands.

**Comment by zakkak** [comment]
@jerboaa FYI: (peak) RSS reporting is now implemented in `master` via https://github.com/oracle/graal/commit/e04a9cd21653bfc5c44c3dc2702b86085216de71

**Comment by jerboaa** [comment]
@zakkak Thanks for the heads-up.

**Pull request closed without merging**
