### PR TITLE
Substitute package info to avoid attempting to load classes #2111

### PR DESCRIPTION
**Pull request by galderz**
Fix for #2111

### CODE REVIEW

**Comment by galderz** [comment]
I work for Red Hat, I should be covered under Red Hat's OCA.

**Comment by dmlloyd** [comment]
I suspect the code will fail the style gate, but I don't recall the command to check it...

**Comment by galderz** [comment]
@dmlloyd indeed it breaks, looking...

**Comment by galderz** [comment]
Fixed `mx eclipseformat` recommendations.

**Comment by dmlloyd** [comment]
Still fails: https://travis-ci.org/oracle/graal/jobs/643518329#L6412

**Comment by galderz** [comment]
Fixed it once more, let's see...

**Comment by eginez** [comment]
@galderz  This should no longer be necessary after: https://github.com/oracle/graal/commit/871f9784f3d7df3556f9388187cdabcdb53751d0

If `package-info` has been registered for reflection the class will now be found in the image.

**Comment by dmlloyd** [comment]
That's interesting.  We discussed and dismissed such a change on the basis that JPMS support is already incomplete, and the result could be incorrect as a result.  But, fixed is fixed I guess! :slightly_smiling_face:

**Comment by eginez** [comment]
Completely understandable. I am closing this PR and its accompanying issue

**Pull request closed without merging**
