### PR TITLE
added speculative guard movement optimization

### PR DESCRIPTION
**Pull request by dougxc**
This is a general approach to moving loop invariant guards outside of loops. It should handle the patterns optimized by https://github.com/oracle/graal/pull/2153 as well as others.

Contributed by:
Lukas Stadler <lukas.stadler@oracle.com>
Roland Schatz <roland.schatz@oracle.com>
Thomas Wuerthinger <thomas.wuerthinger@oracle.com>
Christian Haeubl <christian.haeubl@oracle.com>
Doug Simon <doug.simon@oracle.com>
Tom Rodriguez <tom.rodriguez@oracle.com>

### CODE REVIEW

**Comment by dougxc** [comment]
@rwestrel I think this should cover all the patterns tested for by `org.graalvm.compiler.hotspot.test.RangeCheckPredicatesTest`.
In that light, it would be great if you could have a look at these changes.

**Comment by rwestrel** [comment]
@dougxc thanks for the heads up. I will take a look.

**Comment by dougxc** [comment]
> @dougxc thanks for the heads up. I will take a look.

Thanks. Depending on how much time you need, there's a chance I will merge this PR in the meantime. If you see something that still needs addressing, I will do it in a follow-up PR.

**Comment by dougxc** [comment]
Merged as https://github.com/oracle/graal/commit/d073a81353cc8b13f53fe4e43f2dd915405b09a5

**Comment by dougxc** [comment]
Despite being merged, any feedback you have @rwestrel would still be appreciated.

**Pull request closed without merging**
