### PR TITLE
Fix #1003: Check type of artifact is 'jar' before adding it to classpath

### LINKED ISSUE #1003: native-image-maven-plugin UnsupportedOperationException for project with com.oracle.substratevm:svm:1.0.0-rc12 as dependency
I am using the native-image-maven-plugin to make a native image for a Maven project. This project needs the com.oracle.substratevm:svm:1.0.0-rc12 dependency, because I need to use the com.oracle.svm.core.annotate.* annotations. But that dependency, by default, transitively includes dependencies that are not JAR files. For example, it depends on com.oracle.substratevm:svm-hosted-native-linux-amd64:1.0.0-rc12 which is a *.tar.gz file.

The native-image-maven-plugin fetches all dependencies, and tries to parse them as JAR files. This fails for com.oracle.substratevm:svm-hosted-native-linux-amd64:1.0.0-rc12, and results in a UnsupportedOperationException.

## Work-around

Quick work-around is to exclude all non-JAR dependencies:

```xml
<dependency>
	<groupId>com.oracle.substratevm</groupId>
	<artifactId>svm</artifactId>
	<version>1.0.0-rc12</version>
	<exclusions>
		<exclusion>
			<groupId>com.oracle.substratevm</groupId>
			<artifactId>svm-hosted-native-linux-amd64</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.oracle.substratevm</groupId>
			<artifactId>svm-hosted-native-darwin-amd64</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.oracle.substratevm</groupId>
			<artifactId>svm-hosted-native-windows-amd64</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.graalvm.truffle</groupId>
			<artifactId>truffle-nfi-native-darwin-amd64</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.graalvm.truffle</groupId>
			<artifactId>truffle-nfi-native-linux-amd64</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

Alternatively, if you do not require any transitive dependency, you can use:

```xml
<dependency>
	<groupId>com.oracle.substratevm</groupId>
	<artifactId>svm</artifactId>
	<version>1.0.0-rc12</version>
	<exclusions>
		<exclusion>
			<groupId>*</groupId>
			<artifactId>*</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

(I feel the com.oracle.svm.core.annotate.* classes should be in a separate artifact, but that's a different story.)

## How to reproduce

Change the pom.xml of com.oracle.substratevm:native-image-maven-plugin-test to include the following dependency:

```xml
<dependencies>
	<dependency>
		<groupId>com.oracle.substratevm</groupId>
		<artifactId>svm</artifactId>
	<version>1.0.0-rc12</version>
	</dependency>
</dependencies>
```

And then run `mvn verify` for that project. Output will be:

```
[ERROR] Failed to execute goal com.oracle.substratevm:native-image-maven-plugin:1.0.0-rc12:native-image (default) on project native-image-maven-plugin-test: Execution default of goal com.oracle.substratevm:native-image-maven-plugin:1.0.0-rc12:native-image failed.: UnsupportedOperationException -> [Help 1]
```

### PR DESCRIPTION
**Pull request by Jurrie**

### CODE REVIEW

**Comment by Jurrie** [comment]
Hello @graalvmbot :) I've already signed the OCA. I signed and e-mailed it on the 15th of February this year.

**Comment by sanzinger** [comment]
Hi Jurrie,

thank you for your contribution. The bot checks against the email address provided by the author in the git commit. In this case it is a generic email address from github (`1213142+jurrie@users.noreply.github.com`), which we do not allow. Please amend the commit and change the email address provided with your OCA.

Then I can whitelist this email address for contribution.

Stefan

**Comment by Jurrie** [comment]
Hi @sanzinger,

But that's the email I wrote down on the OCA... :) There was no mention of any requrement on the email for the OCA form. Why should it be a working email address?

Jurrie

**Comment by sanzinger** [comment]
Ok, this is fine for me. (I cannot access the form you have signed) I have started whitelisting email address `1213142+Jurrie@users.noreply.github.com`.

**Comment by sanzinger** [comment]
@Jurrie I have doublechecked with the team managing the OCA list. I am sorry but they have not received the OCA document yet. Please retry sending it to oracle-ca_us [at] oracle [dot] com as instructed [here](https://www.oracle.com/technetwork/community/oca-486395.html).

Stefan

**Comment by olpaw** [comment]
see https://github.com/oracle/graal/issues/1003#issuecomment-468681155

**Pull request closed without merging**
