### PR TITLE
Fix native-image-agent-library macro build with JDK 11.0.11 EA

### LINKED ISSUE #3228: Building the native-image-agent-library macro fails with JDK 11.0.11+2
**Describe the issue**
When trying to build graal and then running the `native-image, --macro:native-image-agent-library` macro fails with:

```
Error: Could not find target method: private java.lang.invoke.MethodHandle com.oracle.svm.methodhandles.Target_java_lang_invoke_MethodHandles_Lookup.maybeBindCaller(com.oracle.svm.methodhandles.Target_java_lang_invoke_MemberName,java.lang.invoke.MethodHandle,java.lang.Class) throws java.lang.IllegalAccessException
```

**Steps to reproduce the issue**
1. build graal master with JDK 11.0.11+2 (e.g. via mandrel-packaging)
2. run `native-image, --macro:native-image-agent-library` after
3. Failure

**Describe GraalVM and your environment:**
 - GraalVM version: ** Graal master, revision 8bbae70e3ad4cc136d2042390b18e829230b7ded**
 - JDK major version:  11.0.11+2
 - OS: Linux
 - Architecture: **AMD64**

**More details**
This is caused by https://bugs.openjdk.java.net/browse/JDK-8235351 which is new in OpenJDK 11.0.11.

See also: https://github.com/graalvm/mandrel/issues/214 where we originally discovered this.

```
DEBUG [build] Launcher line AFTER: exec "${location}/../../../bin/java" --add-exports=java.base/jdk.internal.module=ALL-UNNAMED -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -Dorg.graalvm.version="JDK-8247922-8616-gf38cc1648c2" -Dorg.graalvm.config="(Mandrel Distribution)" --upgrade-module-path ${location}/../../jvmci/graal.jar --add-modules "org.graalvm.truffle,org.graalvm.sdk" --module-path ${location}/../../truffle/truffle-api.jar:${location}/../../jvmci/graal-sdk.jar  "${jvm_args[@]}" -cp "${cp}" 'com.oracle.svm.driver.NativeImage$JDK9Plus' -J--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler  "${launcher_args[@]}"
DEBUG [OperatingSystem] Execute [/disk/graal/upstream-sources/graal/mandrel-build/lib/svm/bin/native-image, --macro:native-image-agent-library] in /disk/graal/upstream-sources/mandrel-packaging
Error: Could not find target method: private java.lang.invoke.MethodHandle com.oracle.svm.methodhandles.Target_java_lang_invoke_MethodHandles_Lookup.maybeBindCaller(com.oracle.svm.methodhandles.Target_java_lang_invoke_MemberName,java.lang.invoke.MethodHandle,java.lang.Class) throws java.lang.IllegalAccessException
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1651)
	at build.buildAgents(build.java:176)
	at build.main(build.java:159)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1642)
	at build.buildAgents(build.java:176)
	at build.main(build.java:159)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```

### PR DESCRIPTION
**Pull request by jerboaa**
Closes #3228

### CODE REVIEW

**Comment by jerboaa** [comment]
@dougxc I'd appreciate if you could take a look at this. It appears you'd be running into it too once you merge JDK-8235351 into labs JDK? Thanks!

**Comment by dougxc** [comment]
@peter-hofer can you please triage this further.
Also, I see there is also a `Target_java_lang_invoke_MethodHandles_Lookup_JDK15` that should probably be consolidated into `Target_java_lang_invoke_MethodHandles_Lookup`.

**Comment by oraluben** [comment]
> Also, I see there is also a `Target_java_lang_invoke_MethodHandles_Lookup_JDK15` that should probably be consolidated into `Target_java_lang_invoke_MethodHandles_Lookup`.

Right. Please also consolidate those two classes if possible.

**Comment by jerboaa** [comment]
@oraluben Thanks for helping to get this integrated.

**Pull request merged**
