### PR TITLE
svm: fix for JDK 21.0.4 after the downport of "8315373: Change VirtualThread to unmount after freezing, re-mount before thawing" and dependnet changes

### PR DESCRIPTION
**Pull request by simonis**
This change fixes svm after the downport of [JDK-8315373](https://bugs.openjdk.org/browse/JDK-8315373) (which included [JDK-8312498](https://bugs.openjdk.org/browse/JDK-8312498), [JDK-8312777](https://bugs.openjdk.org/browse/JDK-8312777), [JDK-8321270](https://bugs.openjdk.org/browse/JDK-8321270), [JDK-8322818](https://bugs.openjdk.org/browse/JDK-8322818), [JDK-8323002](https://bugs.openjdk.org/browse/JDK-8323002), [JDK-8323296](https://bugs.openjdk.org/browse/JDK-8323296), [JDK-8316924](https://bugs.openjdk.org/browse/JDK-8316924)) to OpenJDK 21.0.4. It does this by downporting 
- [[svm: adopt "JDK-8312498 Thread::getState and JVM TI GetThreadState sh…](https://github.com/graalvm/graalvm-for-jdk21-community-backports/commit/a65b9e93f9792b15808789104b8c084f6f23e1f9)
- [[GR-48899] Support TIMED_WAITING for virtual threads](https://github.com/graalvm/graalvm-for-jdk21-community-backports/commit/142c5f49593c79a87bf150adfbb37b825166ecd4)
- [svm: adopt "JDK-8321270: Virtual Thread.yield consumes parking permit…](https://github.com/graalvm/graalvm-for-jdk21-community-backports/commit/aa1c4a9e9502736e60efc5401c944971701238c6)

and adopting them to work on JDK 21.

I'm not sure if this fix should be done in this repository or in the [master](https://github.com/graalvm/graalvm-for-jdk21-community-backports) branch of the [graalvm/graalvm-for-jdk21-community-backports](https://github.com/graalvm/graalvm-for-jdk21-community-backports) repository which currently matches the [release/graal-vm/23.1](https://github.com/oracle/graal/tree/release/graal-vm/23.1) branch of this repository. I don't understand how these two branches/repositories are related, if one is synced into the other automatically or if one of them is abandoned. For any case I've also submitted this PR to  [graalvm/graalvm-for-jdk21-community-backports](https://github.com/graalvm/graalvm-for-jdk21-community-backports) as well ([see PR](https://github.com/graalvm/graalvm-for-jdk21-community-backports/pull/1)). Feel free to close one of them but please be so kind and explain the relationship of the two branches/repositories :)

### CODE REVIEW

**Comment by simonis** [comment]
> Thank you for your pull request and welcome to our community! To contribute, please sign the Oracle Contributor Agreement (OCA). The following contributors of this PR have not signed the OCA:
> 
>     * PR author: [volker.simonis@gmail.com](mailto:volker.simonis@gmail.com) (@simonis)
> 
> 
> To sign the OCA, please [create an Oracle account](https://profile.oracle.com/myprofile/account/create-account.jspx) and sign the OCA in [Oracle's Contributor Agreement Application](https://oca.opensource.oracle.com/).
> 
> When signing the OCA, please provide your GitHub username. After signing the OCA and getting an OCA approval from Oracle, this PR will be automatically updated.
> 
> _If you are an Oracle employee, please make sure that you are a member of the main [Oracle GitHub organization](https://github.com/oracle), and your [membership in this organization is public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership)._

Please note that I'm an OpenJDK Contributor already (['simonis' in the OpenJDK Census](https://openjdk.org/census#simonis) and [member of the OpenJDK Github organization](https://github.com/orgs/openjdk/people?query=simonis)). I've already personally signed the Sun Contributor Agreement but am also covered by Amazon's company-wide OCA. Please let me know if there's anything else I have to do?

**Comment by ezzarghili** [comment]
> 
Feel free to close one of them but please be so kind and explain the relationship of the two branches/repositories [graalvm/graalvm-for-jdk21-community-backports](https://github.com/graalvm/graalvm-for-jdk21-community-backports) [graalvm/graalvm-for-jdk17-community-backports](https://github.com/graalvm/graalvm-for-jdk17-community-backports)  was created based on discussion on the GraalVM Meetup with the contributors community, we no longer provide community builds for JDK 17 and JDK 21, those repos are where we share the open parts of GraalVM for the community (i.e mandrel) that wishes to still continue providing builds for them, we also use those repos for getting backport requests .

**Comment by simonis** [comment]
> > Feel free to close one of them but please be so kind and explain the relationship of the two branches/repositories
> 
> [graalvm/graalvm-for-jdk21-community-backports](https://github.com/graalvm/graalvm-for-jdk21-community-backports) [graalvm/graalvm-for-jdk17-community-backports](https://github.com/graalvm/graalvm-for-jdk17-community-backports) were created based on discussions in the GraalVM Meetup with the contributors' community, we no longer provide community builds for JDK 17 and JDK 21, those repos are where we share the open parts of GraalVM for the community (i.e mandrel) that wishes to still continue providing builds for them, we also use those repos for getting backport requests .

@ezzarghili thank you for this information. So based on what you are saying, I should close this PR and follow up on the [PR](https://github.com/graalvm/graalvm-for-jdk21-community-backports/pull/1) in the  [graalvm/graalvm-for-jdk21-community-backports](https://github.com/graalvm/graalvm-for-jdk21-community-backports) repository, right?

You also say that "*you no longer provide community builds for JDK 17 and JDK 21*" but I was a little confused why you've then still downported 219 changes after the release of [graal-23.1.2](https://github.com/oracle/graal/tree/graal-23.1.2) to the [release/graal-vm/23.1](https://github.com/oracle/graal/tree/release/graal-vm/23.1) branch (with the last change being [donwported just last week](https://github.com/oracle/graal/commit/cee7cbdae517c60457a4f6a5abf58d6ed06a0c7d)) apparently in the preparation of the GraalVM 23.1.3 release as the "[New dev cycle GraalVM 23.1.3](https://github.com/oracle/graal/commit/53cf8c03139)" commit indicates? So after all, will there be a final 23.1.3 release/tag in this repository or not? This obviously doesn't necessarily mean that you also have to provide a community build for that tag.

The other question would be who is in charge of [graalvm/graalvm-for-jdk21-community-backports](https://github.com/graalvm/graalvm-for-jdk21-community-backports)? I.e. who has the right to review and approve pull requests? Bacause in contrast to this PR, I haven't got any reaction on my other  [PR](https://github.com/graalvm/graalvm-for-jdk21-community-backports/pull/1) in  [graalvm/graalvm-for-jdk21-community-backports](https://github.com/graalvm/graalvm-for-jdk21-community-backports) until now.

**Comment by fniephaus** [comment]
Hi Volker, thanks a lot for the downport! As @ezzarghili mentioned, we are using the new repositories for community backports, so I will close this PR for now.

Also, apologies for the slow response. I self-assigned this when I saw it three days ago and requested a review. I then de-prioritized this because we are getting very close to the release of GraalVM for JDK 22. That, and the fact that this is one of the first community backport requests, are why we haven't had time to answer your related questions. Let's keep the PRs technical and continue the general discussion about backports on Slack (I see you've posted there as well).

**Pull request closed without merging**
