### PR TITLE
Fix typo 'initalize' -> 'initialize'

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by zakkak** [comment]
This is now rebased, could someone please review and merge?

**Comment by zakkak** [comment]
> This is now rebased, could someone please review and merge?

Kind reminder

**Review by adinn — APPROVED** [review]
Looks good to me. I found no other similar typos in the src tree

**Comment by zakkak** [comment]
@mcraj017 can you please have a look at this?

**Pull request merged**
