### PR TITLE
[GR-47922] Enforce `-H:±UnlockExperimentalVMOptions` in CI.

### PR DESCRIPTION
**Pull request by graalvmbot**
This PR sets `NATIVE_IMAGE_EXPERIMENTAL_OPTIONS_ARE_FATAL=true` in CI to ensure that gates are properly unlocking experimental options. The PR also adjusts various mx/CI infrastructure bits and fixes a bug in the unlocking mechanism itself.

### CODE REVIEW

**Comment by zakkak** [comment]
Hi @fniephaus, although this makes sense as the next step we still see 3rd party libraries using experimental VM options, e.g. https://github.com/netty/netty/issues/13595 and https://github.com/neo4j/neo4j-java-driver/issues/1498, so I expect significant disruption if this goes in now.

I am afraid that would possibly force frameworks to just pass `-H:+UnlockExperimentalVMOptions` in the beginning of the `native-image` arguments, which is not desirable.

**Comment by zakkak** [comment]
Furthermore I don't see the PR resolving the "Bug fixes and improvements" and "API changes" parts of https://github.com/oracle/graal/issues/7370 is that intentional are they resolved in separate PRs?

**Comment by fniephaus** [comment]
Hey @zakkak, are you suggesting that we enforce unlocking in a later release of GraalVM? The JDK 22 release is half a year away from the JDK 21 release (that's where we introduced `-H:+UnlockExperimentalVMOptions`) , and the JDK 23 release is a year away.

**Comment by fniephaus** [comment]
> Furthermore I don't see the PR resolving the "Bug fixes and improvements" and "API changes" parts of https://github.com/oracle/graal/issues/7370 is that intentional are they resolved in separate PRs?

They will be resolved in separate PRs.

**Comment by zakkak** [comment]
> Hey @zakkak, are you suggesting that we enforce unlocking in a later release of GraalVM? The JDK 22 release is half a year away from the JDK 21 release (that's where we introduced `-H:+UnlockExperimentalVMOptions`) , and the JDK 23 release is a year away.

Not necessarily, I would suggest delaying the merge of the PR for the time being to see how the ecosystem adapts. We still have enough time for the code freeze, right?

> They will be resolved in separate PRs.

In that case it would make more sense to merge those PRs first, no?

**Comment by fniephaus** [comment]
> Not necessarily, I would suggest delaying the merge of the PR for the time being to see how the ecosystem adapts. We still have enough time for the code freeze, right?

Sure, code freeze is in December, and the freeze is much longer (3 months as opposed to one month). Keep in mind that doing this now will only affect end-users that use a dev build.

> In that case it would make more sense to merge those PRs first, no?

It depends. On #7370, we said that enabling this has the highest priority.

**Comment by fniephaus** [comment]
I have adjusted this PR so that it doesn't change the behavior just yet. Instead, we use `NATIVE_IMAGE_EXPERIMENTAL_OPTIONS_ARE_FATAL=true` in CI.

**Pull request merged**
