### PR TITLE
Ensure locator/installer build for JDK11 (fixes #1392)

### LINKED ISSUE #1392: `gu` in JDK11 distribution is invalid
When building the JDK11-centric distribution, the `bin/gu` still presumes it's under a non-existent JRE.

As it's an extracted dependency (I guess?) I'm finding no simple way to rewrite or provide an alternative `gu_jdk11` source for the script.

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Adjust the javaCompliance to allow for java 1.8+ instead of
exactly 1.8.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Once again I don’t think I caused this CI failure.

**Comment by bobmcwhirter** [comment]
Rebased and force-pushed just to trigger another CI run, hopefully CI this time.

**Comment by bobmcwhirter** [comment]
Partial CI failure with 

    IOError: [Errno 32] Broken pipe

Do with it as you like.

**Comment by dmlloyd** [comment]
Any updates on this one?

**Comment by bobmcwhirter** [comment]
Ping?

**Comment by bobmcwhirter** [comment]
The CI check didn't even run...

**Comment by gilles-duboscq** [comment]
@sdedic currently has a PR internally that does exactly this for `org.graalvm.component.installer` and its tests.
@dougxc is currently working on 11+ support in general in the GraalVM and is dealing with `com.oracle.graalvm.locator` (which definitely doesn't work on 9+ currently).

I'm not sure it's worth it to integrate these workarounds now.

**Comment by bobmcwhirter** [comment]
If there's 2+ better/different solutions floating around somewhere, feel free to close this.

**Comment by sdedic** [comment]
Compliance was fixed for `gu`; locator was moved elsewhere.

**Pull request closed without merging**
