### PR TITLE
Aarch64 aot

### PR DESCRIPTION
**Pull request by theRealAph**
Changes in Graal needed to support AOT compilation on AArch64.

### CODE REVIEW

**Comment by dougxc** [comment]
I assume these change has been tested locally with necessary hotspot and jvmci changes? There's not much extra testing we can do at this point in time given limited ARM64 hardware access.

**Comment by theRealAph** [comment]
The OpenJDK changes are at http://cr.openjdk.java.net/~aph/8185505-1/

I have a bunch of testers looking at this.

**Comment by dougxc** [comment]
Ok, once it passes the Travis gate and your testers give it the ok, I'll integrate this change.

**Comment by nsjian** [comment]
We've also tested this changeset locally with JDK patch, and it worked fine.

**Comment by theRealAph** [comment]
This should be good to merge now, Doug. Thanks for the help.

**Comment by dougxc** [comment]
We will try and merge this as soon as possible.

**Pull request merged**
