### PR TITLE
Allow disabling SO_LINGER on java.net.Socket

### PR DESCRIPTION
**Pull request by Sanne**
Fixes ##1087

I'm a Red Hat employee so I believe I won't need to sign an individual contributor agreement.

It's my first contribution. Please let me know if I should do anything else; I'm wondering also if I should add a regression test? I could use a pointer to an example of how you want such tests structured.

Thanks!

### CODE REVIEW

**Comment by Sanne** [comment]
@graalvmbot I'm a Red Hat employee so I believe I won't need to sign an individual contributor agreement.

**Comment by cstancu** [comment]
@Sanne I update the OCA signatory list with your email.

**Comment by Sanne** [comment]
thanks @cstancu !

**Comment by Sanne** [comment]
pushed an improved commit, after feedback on #1087

**Pull request merged**
