### PR TITLE
Add TruffleBF to listed languages

### PR DESCRIPTION
**Pull request by tisonkun**
Actually it's a completed implementation :)

### CODE REVIEW

**Comment by tisonkun** [comment]
OCA submitted and waiting for review...

**Comment by tisonkun** [comment]
ping @olyagpl as a reminder >_<

**Review by fniephaus — APPROVED** [review]

**Comment by fniephaus** [comment]
Thanks for the PR, @tisonkun, and apologies for the delay. This is now merged via #5988.

**Comment by tisonkun** [comment]
@fniephaus Thanks for your update!

**Pull request closed without merging**
