### PR TITLE
[GR-53920] Use hashed lookup in the secondary supers array.

### PR DESCRIPTION
**Pull request by graalvmbot**
This PR
1. removes update of secondary supers cache. Now the only usage is comparing the offset of the cache field against ` _super_check_offset` to determine if it is primary super or secondary super; https://github.com/openjdk/jdk/blob/4083255440cfbf39b9683ea88a433d71ec6111e7/src/hotspot/share/oops/klass.hpp#L132-L134
2. ports hashed lookup in the secondary supers array;
3. introduces an AMD64 match rule that replaces test with bit test to reduce size;
4. depends on upstream PR https://github.com/openjdk/jdk/pull/19176

See TypeCheckSnippetUtils#checkSelfAndSupers for a summary of the hashed lookup
Original HotSpot PR https://github.com/openjdk/jdk/pull/18309

### CODE REVIEW

**Comment by mur47x111** [comment]
In preparation of secondary_super_cache removal, we are adapting the hashed lookup in the secondary supers array. Still, we have some code checking if super_check_offset is equal to offset of _secondary_super_cache.

@theRealAph It would be great if you could share your plan regarding the following 2 items:

> In the future I'd like to delete the secondary super cache

1. If this is not gonna happen in the foreseeable future, we will merge as is.

2. Is there a plan to backport to 21u? We will maintain both versions if not.

**Comment by theRealAph** [comment]
> In preparation of secondary_super_cache removal, we are adapting the hashed lookup in the secondary supers array. Still, we have some code checking if super_check_offset is equal to offset of _secondary_super_cache.
> 
> @theRealAph It would be great if you could share your plan regarding the following 2 items:
> 
> > In the future I'd like to delete the secondary super cache

This is a fairly long way off. I'd think at least a year.

>     1. If this is not gonna happen in the foreseeable future, we will merge as is.
> 
>     2. Is there a plan to backport to 21u? We will maintain both versions if not.

Yes, after it's had a little time is JDK 23.

**Comment by pjfanning** [comment]
Java 23 reached GA in Sept 2024, 3 months ago. Would it be possible to consider backporting to Java 21 now?

**Comment by zakkak** [comment]
> Java 23 reached GA in Sept 2024, 3 months ago. Would it be possible to consider backporting to Java 21 now?

@pjfanning it looks like @theRealAph is working on this in https://github.com/openjdk/jdk21u-dev/pull/1090

**Comment by mur47x111** [comment]
Once @theRealAph integrated the jdk21u PR, we will enable it in Graal when updating to the next JDK 21 build.
```
diff --git a/compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/hotspot/replacements/TypeCheckSnippetUtils.java b/compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/hotspot/replacements/TypeCheckSnippetUtils.java
index cbb342cebda..489566385f4 100644
--- a/compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/hotspot/replacements/TypeCheckSnippetUtils.java
+++ b/compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/hotspot/replacements/TypeCheckSnippetUtils.java
@@ -96,7 +96,7 @@ public class TypeCheckSnippetUtils {
     // @formatter:on
     static boolean checkSecondarySubType(KlassPointer t, KlassPointer s, boolean isTAlwaysAbstract, Counters counters) {
         // if (S.cache == T) return true
-        if ((JavaVersionUtil.JAVA_SPEC == 21 || (JavaVersionUtil.JAVA_SPEC >= 23 && useSecondarySupersCache(INJECTED_VMCONFIG))) &&
+        if (useSecondarySupersCache(INJECTED_VMCONFIG) &&
                         probability(FREQUENT_PROBABILITY, s.readKlassPointer(secondarySuperCacheOffset(INJECTED_VMCONFIG), SECONDARY_SUPER_CACHE_LOCATION).equal(t))) {
             counters.cacheHit.inc();
             return true;
@@ -108,7 +108,7 @@ public class TypeCheckSnippetUtils {
             return true;
         }
 
-        if (JavaVersionUtil.JAVA_SPEC == 21 || (JavaVersionUtil.JAVA_SPEC >= 23 && !useSecondarySupersTable(INJECTED_VMCONFIG))) {
+        if (!useSecondarySupersTable(INJECTED_VMCONFIG)) {
             Word secondarySupers = s.readWord(secondarySupersOffset(INJECTED_VMCONFIG), SECONDARY_SUPERS_LOCATION);
             int length = secondarySupers.readInt(metaspaceArrayLengthOffset(INJECTED_VMCONFIG), METASPACE_ARRAY_LENGTH_LOCATION);
             for (int i = 0; i < length; i++) {
```

**Pull request closed without merging**
