### PR TITLE
Implement stackwalker and logging

### PR DESCRIPTION
**Pull request by johanvos**
Based on https://github.com/oracle/graal/pull/734 by @dmlloyd 
This adds the StackWalker implementation and some fixes
for java.util.logging to work

### CODE REVIEW

**Comment by johanvos** [comment]
This addresses #1172

**Comment by dmlloyd** [comment]
Could you please amend the commit with my author info, and add yourself as "Co-authored-by"?

Thanks.

**Comment by dmlloyd** [comment]
Or better yet, keep my original commit and add a second one with the rest?

**Comment by johanvos** [comment]
Or even better, update your original PR with my suggestions (I don't need any credits, just a working implementation).

**Comment by johanvos** [comment]
Note that RETAIN_CLASS_REFERENCE is not yet supported, but I recommend that to be a separate issue.

**Comment by dmlloyd** [comment]
I have no problem doing that, but for future reference, squashing changes together makes that kind of thing a bit difficult.

**Comment by johanvos** [comment]
If you can rebase your original commit to master, I can add another commit. But that didn't turn out to be trivial to me, so I restarted from master.

**Comment by vjovanov** [comment]
@dmlloyd can you do the changes so I can start the merge process.

**Comment by dmlloyd** [comment]
I'll be making these changes today.

**Comment by dmlloyd** [comment]
@johanvos I've updated #734 and pushed the remaining changes that I found to https://github.com/dmlloyd/graal/tree/johanvos for you to look at.  That branch is based on #734 but I think both commits could probably be independent.

**Comment by dmlloyd** [comment]
Also I broke the change into two commits.  In particular I didn't understand the purpose of the class loader change so you might want to amend the description.

**Comment by vjovanov** [comment]
This PR is now on #734.

**Pull request closed without merging**
