### PR TITLE
[GR-54703] Add reflection metadata for jfrTracing field.

### PR DESCRIPTION
**Pull request by graalvmbot**

### CODE REVIEW

**Comment by zakkak** [comment]
Hello @jovanstevanovic @ansalond, we (the mandrel team) would like to request this to get backported to 24.1. What do you think?

**Comment by jovanstevanovic** [comment]
Hey @zakkak, no problem, I can do that.

**Comment by zakkak** [comment]
Great, thanks!

**Comment by jovanstevanovic** [comment]
The fix is backported.

**Comment by zakkak** [comment]
FTR the backport PR is https://github.com/oracle/graal/pull/9380

**Pull request merged**
