### PR TITLE
JDK-8191339: [JVMCI] BigInteger compiler intrinsics on Graal.

### PR DESCRIPTION
**Pull request by phedlin**
Added simplistic test cases and benchmark for BigInteger intrinsics.

Used in order to test JDK change.

### CODE REVIEW

**Comment by phedlin** [comment]
I have no idea what the blocking test(s) are.

**Comment by dougxc** [comment]
@rschatz it seems as though the `Run Sulong interop tests as native-image` [hangs](https://travis-ci.org/oracle/graal/jobs/428544007) - is this a known problem?

@phedlin the PR can be integrated without passing these tests.

**Comment by rschatz** [comment]
Yes, this is a known problem and has nothing to do with this PR.

**Comment by phedlin** [comment]
Anyone to push this along?

**Comment by mur47x111** [comment]
I will take care of this. Btw, this PR contains only test case and benchmark?

**Comment by phedlin** [comment]
Yes, the enabler is part of JDK (only).

**Pull request merged**
