### PR TITLE
Add C++ interoperability properties

### PR DESCRIPTION
**Pull request by pichristoph**
Previous description does not mention how method resolution is done if C++ methods are involved - this is now added. Feel free to give feedback if something of the content should be changed. 
Mainly for internal discussion with Sulong team (but not restricted to).

### CODE REVIEW

**Comment by oubidar-Abderrahim** [comment]
Hi, @pichristoph, Thank you for contributing to GraalVM, could you please provide answers to the following questions?

Is your PR complete and ready for review?
Did you have a conversation about these changes with some team members and you would like for them to review this as they have more context? please mention them
Do your changes rely on other changes made in a separate open PR? if yes please link it to this one

**Comment by pichristoph** [comment]
Hi @oubidar-Abderrahim,
thanks for asking and reminding! It seems that this PR has been forgotten to be finally discussed and merged - I will talk to @rschatz who is also in the Sulong team and who has a good context about the Sulong code base in general. The PR is ready for review.

**Comment by oubidar-Abderrahim** [comment]
We apologize for that, we're in the middle of our release cycle so the Dev teams are super busy currently, we will check this PR as soon as possible

**Comment by pichristoph** [comment]
@oubidar-Abderrahim no problem :) Thanks!

**Review by rschatz — APPROVED** [review]
Sorry for not reviewing this earlier. Looks good, thanks!

**Comment by oubidar-Abderrahim** [comment]
@rschatz Do you want me to mirror this PR to ol-bitbucket?

**Pull request merged**
