### PR TITLE
Fix issue #2493: stop reordering two IF statemenets if one of their condition is signe…

### PR DESCRIPTION
**Pull request by lic9**
…d and the other is unsigned.

### CODE REVIEW

**Comment by lic9** [comment]
Hi @dougxc, could you please help take a look? Thanks!

**Comment by dougxc** [comment]
Thanks for the PR @lic9 . However, @tkrodriguez already has a fix in the pipeline that will address this problem.

**Comment by dougxc** [comment]
Correction: it is already merged in 2dfa6ab92a02f4c018376190ced992be9dd066e3

**Comment by lic9** [comment]
That’s much better! Thanks @dougxc!

**Comment by helloguo** [comment]
Any plan to backport the fix 2dfa6ab into 19.3.1?

**Comment by dougxc** [comment]
I think 19.3.3 would be the next back-port target right @gilles-duboscq?

**Comment by gilles-duboscq** [comment]
Indeed

**Comment by dougxc** [comment]
Ok, just confirming, it will be in 19.3.3.

**Pull request closed without merging**
