### PR TITLE
[GR-51624] Update java.security path.

### PR DESCRIPTION
**Pull request by OlgaMaciaszek**
That's what seems to do the trick.

### CODE REVIEW

**Comment by vjovanov** [comment]
Thanks for your contribution! We will merge this soon.

**Review by vjovanov — APPROVED** [review]
LGTM

**Review by fniephaus — APPROVED** [review]
LGTM, thanks for the fix @OlgaMaciaszek!

**Comment by fniephaus** [comment]
Thanks for the contribution. This is merged via #8259.

**Pull request closed without merging**
