### PR TITLE
[GR-48659] Remove the SpawnIsolate option from the documentation.

### PR DESCRIPTION
**Pull request by graalvmbot**
https://www.graalvm.org/latest/reference-manual/native-image/debugging-and-diagnostics/DebugInfo/ should not reference the `SpawnIsolate` option any longer.

### CODE REVIEW

**Comment by wirthi** [comment]
This PR is removing the mention of the `SpawnIsolate` option from documentation. We want to avoid this being mentioned by default, it should not be used. And nowadays it does not seem necessary, at least with current versions of GraalVM and GDB.

**Review by olpaw — APPROVED** [review]

**Comment by wirthi** [comment]
@adinn are you fine with merging that?

**Comment by wirthi** [comment]
@adinn  I'll merge this later this week unless you object.

**Comment by adinn** [comment]
> @adinn I'll merge this later this week unless you object.
@wirthi Sorry, I missed your first comment. Yes, please proceed with the change.

**Pull request merged**
