### PR TITLE
[GR-22580] Update to CI spec version 3 and explicitly import mx and python.

### PR DESCRIPTION
**Pull request by graalvmbot**
This PR updates the Oracle CI config such that `mx` is not provisioned by default but must be explicitly requested as a dependency.

Also, since `python3` is now the default on PATH, it's necessary to use a python3 compliant version of `pylint`. We've settled on 2.4.4.

Note that some builders explicitly prepend a specific version of `python` to the PATH so we also need to define `MX_PYTHON` to be `python3.8` so that we ensure mx runs with the right python executable.

Summarizing, here are the effective changes reflecting the above:
```
{
    specVersion: "3",
    python_version: "3",
    packages+: {
        mx: "HEAD",
        python3: "==3.8.10",
        pylint: "==2.4.4",
    }
    environment+: {
        MX_PYTHON: "python3.8"
    }
}
```

### CODE REVIEW

**Comment by dougxc** [comment]
@zakkak can you please look at the Quarkus failures to see if they might be caused by the changes to `.github/workflows/quarkus.yml`.

**Comment by zakkak** [comment]
> @zakkak can you please look at the Quarkus failures to see if they might be caused by the changes to `.github/workflows/quarkus.yml`.

Hi @dougxc , the failures in Quarkus seem related to https://github.com/oracle/graal/commit/8a42ff96c5bee396affbeeab8251e7dd195b6554 as mentioned in https://github.com/oracle/graal/issues/4388#issuecomment-1066898555. Your changes to quarkus.yml look good to me, thanks!

**Comment by dougxc** [comment]
@zakkak there seems to be a problem here: https://github.com/oracle/graal/actions/runs/2243992248/workflow
As far as I can tell, the [`workflow_dispatch`](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) event was added here: https://github.com/oracle/graal/commit/78a1d958b32dbbc42ae407b38faa8687d702c9f7#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R10
Do you know what's wrong?

**Comment by zakkak** [comment]
@dougxc , it looks like GH enabled some stricter checking on the yaml syntax, it broke the mandrel pipelines as well. See https://github.com/oracle/graal/pull/4522 for the fix.

**Pull request merged**
