### PR TITLE
Fixes 1519 - Silence unfixable Unsafe automatic substitutions in the JDK

### LINKED ISSUE #1519: JDK11: Silence additional unsafe offset warnings we can't fix.

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Fixes #1519

### CODE REVIEW

**Comment by cstancu** [comment]
@bobmcwhirter what is the exact warning in this case?

**Comment by bobmcwhirter** [comment]
Unsafe offset usage not followed by a sign-extend or store, involving those additional JDK11 classes, just like InnocuousThread.

**Comment by bobmcwhirter** [comment]
fwiw, I think my other PR obviates the need for this one. Not completely certain, but it attempts to deal with entire classes of usage instead of just whitelisting unfixable JDK whinging.

**Comment by cstancu** [comment]
Yes, I thought that the other PR might actually fix this case too. Can you confirm that that's the case?

**Comment by bobmcwhirter** [comment]
Yeah, lemme verify. Will get back to you later today or in the AM (US-Eastern).

**Comment by bobmcwhirter** [comment]
Seems not.

```
Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of java.util.concurrent.atomic.AtomicReferenceArray. Detailed failure reason(s):
```

Of course no actual detailed failure reasons actually follow in the output.

I'll dig in tomorrow some more.

**Comment by bobmcwhirter** [comment]
I augmented #1405 which now does include a non-whitelisting fix for this class of warnings. Closing this PR.

**Pull request closed without merging**
